"""
Standalone Production RAG Server
Auto-generated by Autonomous RAG Factory
"""
import os
import uvicorn
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from typing import List, Optional

# Embedded Core Logic
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings
import httpx

app = FastAPI(title="Self-Hosted Production RAG API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_NAME = "llama3.2:1b"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
DB_PATH = Path("./vector_db")

print(f"📦 Loading Local Embedding Model: {EMBEDDING_MODEL}...")
embedder = SentenceTransformer(EMBEDDING_MODEL)

print(f"🗄️ Connecting to Embedded ChromaDB at: {DB_PATH}...")
chroma_client = chromadb.PersistentClient(path=str(DB_PATH), settings=Settings(anonymized_telemetry=False))
collections = chroma_client.list_collections()
collection = collections[0] if collections else chroma_client.get_or_create_collection("rag_knowledge_base")

class QueryRequest(BaseModel):
    question: str
    top_k: Optional[int] = 3

class Citation(BaseModel):
    source_file: str
    relevance_score: float
    text: str

class QueryResponse(BaseModel):
    answer: str
    citations: List[Citation]
    grounded: bool

@app.post("/api/query", response_model=QueryResponse)
async def query_rag(req: QueryRequest):
    query_vec = embedder.encode(req.question, convert_to_numpy=True).tolist()
    results = collection.query(query_embeddings=[query_vec], n_results=req.top_k, include=["documents", "metadatas", "distances"])
    
    citations = []
    relevant_chunks = []
    if results["ids"] and len(results["ids"][0]) > 0:
        for i in range(len(results["ids"][0])):
            dist = results["distances"][0][i]
            sim = max(0.0, 1.0 - dist)
            doc_text = results["documents"][0][i]
            meta = results["metadatas"][0][i]
            if sim >= 0.20:
                citations.append(Citation(source_file=meta.get("source_file", "unknown"), relevance_score=round(sim, 4), text=doc_text))
                relevant_chunks.append(f"[Document: {meta.get('source_file', 'unknown')}]\n{doc_text}")

    if not relevant_chunks:
        return QueryResponse(answer="I could not find any information about this in the documentation.", citations=[], grounded=False)

    context_str = "\n\n".join(relevant_chunks)
    prompt = f"Context:\n{context_str}\n\nQuestion: {req.question}\n\nAnswer based only on the context:"
    
    system_msg = "You are a precise enterprise assistant. Answer directly using only facts from the context."
    payload = {
        "model": MODEL_NAME,
        "messages": [{"role": "system", "content": system_msg}, {"role": "user", "content": prompt}],
        "stream": False,
        "options": {"temperature": 0.1, "num_ctx": 4096, "num_gpu": 99}
    }

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            res = await client.post("http://localhost:11434/api/chat", json=payload)
            res.raise_for_status()
            ans_text = res.json().get("message", {}).get("content", "").strip()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ollama error: {str(e)}. Make sure Ollama is running.")

    return QueryResponse(answer=ans_text, citations=citations, grounded=True)

@app.get("/", response_class=HTMLResponse)
def serve_ui():
    ui_path = Path("./index.html")
    if ui_path.exists():
        return ui_path.read_text(encoding="utf-8")
    return "<h1>Production RAG API is Running! Open /docs for API schema.</h1>"

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
