import os
import re
import shutil
import zipfile
import subprocess
from pathlib import Path
from typing import Optional
from server.sessions.session_manager import RAGSession


class RAGPackager:
    """
    Bundles a RAG session into a standalone, turnkey production ZIP package.
    """

    def __init__(self, export_output_dir: Path | str = "./data/exports"):
        self.output_dir = Path(export_output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _safe_copy_file(src: Path, dst: Path) -> bool:
        """Safely copy a file, skipping identical files and ignoring transient Windows file locks."""
        try:
            if not src.exists():
                return False
            if dst.exists():
                try:
                    if dst.stat().st_size == src.stat().st_size:
                        return True
                except Exception:
                    return True
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            return True
        except Exception:
            return dst.exists()

    @staticmethod
    def _safe_write_text(path: Path, content: str, encoding: str = "utf-8") -> bool:
        """Safely write text content, creating parents and ignoring locks if file already exists."""
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding=encoding)
            return True
        except Exception:
            return path.exists()

    def _generate_standalone_server_code(self, model_name: str, embedding_model: str, indexed_files: list) -> str:
        files_json = str(indexed_files)
        return f'''"""
Standalone Production RAG Server with Multi-Turn Memory & Attention Reranking
Auto-generated by Autonomous RAG Factory (Mi:RAG)
"""
import sys
import os
# Ensure standard streams exist when running without console under pythonw.exe
if sys.stdout is None:
    sys.stdout = open(os.devnull, "w", encoding="utf-8")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w", encoding="utf-8")

if sys.platform == "win32":
    for p in [Path("./assets/vc_runtimes"), Path(__file__).resolve().parent / "assets" / "vc_runtimes", Path(".")]:
        if p.exists() and hasattr(os, "add_dll_directory"):
            try:
                os.add_dll_directory(str(p.resolve()))
            except Exception:
                pass

import re
import uuid
import shutil
import threading
import time
import uvicorn
from pathlib import Path
from fastapi import FastAPI, HTTPException, Request, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import List, Optional, Dict, Any

import httpx

app = FastAPI(title="Standalone Turnkey RAG Assistant", version="2.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_NAME = "{model_name}"
EMBEDDING_MODEL = "{embedding_model}"
DB_PATH = Path("./vector_db")
CHAT_DB_PATH = Path("./chat_history.db")
IMAGES_DIR = Path("./images")
INDEXED_FILES = {files_json}

IMAGES_DIR.mkdir(parents=True, exist_ok=True)
if IMAGES_DIR.exists():
    app.mount("/images", StaticFiles(directory=str(IMAGES_DIR)), name="images")

STATIC_DIR = Path("./static")
if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

ENGINE_STATE = {{
    "ready": False,
    "progress": 20,
    "step": "Connecting local server...",
    "details": "Binding local port and starting HTTP daemon...",
    "error": None
}}
init_event = threading.Event()
embedder = None
chroma_client = None
collection = None

def init_engine_background():
    global embedder, chroma_client, collection, ENGINE_STATE
    import sys
    sys.modules["torchvision"] = None
    sys.modules["torchvision.io"] = None
    try:
        # Step 1: ChromaDB
        ENGINE_STATE["step"] = "Mounting Vector Database..."
        ENGINE_STATE["details"] = "Opening indexed ChromaDB collection..."
        ENGINE_STATE["progress"] = 40
        import chromadb
        from chromadb.config import Settings
        chroma_client = chromadb.PersistentClient(path=str(DB_PATH), settings=Settings(anonymized_telemetry=False))
        collections = chroma_client.list_collections()
        collection = collections[0] if collections else chroma_client.get_or_create_collection("rag_knowledge_base")

        # Step 2: Check Local AI Engine
        ENGINE_STATE["step"] = "Checking Local AI Engine..."
        ENGINE_STATE["details"] = f"Connecting to Ollama for {{MODEL_NAME}}..."
        ENGINE_STATE["progress"] = 65
        try:
            with httpx.Client(timeout=2.0) as client:
                client.get("http://localhost:11434/api/tags")
        except Exception:
            pass

        # Step 3: Neural Embedding Weights
        ENGINE_STATE["step"] = "Loading Neural Embedding Weights..."
        ENGINE_STATE["details"] = f"Initializing {{EMBEDDING_MODEL}}..."
        ENGINE_STATE["progress"] = 85
        try:
            from sentence_transformers import SentenceTransformer
            try:
                embedder = SentenceTransformer(EMBEDDING_MODEL, local_files_only=True)
            except Exception:
                try:
                    embedder = SentenceTransformer("BAAI/bge-base-en-v1.5", local_files_only=True)
                except Exception:
                    embedder = SentenceTransformer(EMBEDDING_MODEL)
        except Exception as embed_err:
            print(f"[!] SentenceTransformer notice: {{embed_err}}")
            embedder = None

        # Step 4: Ready
        ENGINE_STATE["step"] = "Ready"
        ENGINE_STATE["details"] = "Turnkey Assistant online and grounded."
        ENGINE_STATE["progress"] = 100
        ENGINE_STATE["ready"] = True
    except Exception as e:
        ENGINE_STATE["error"] = str(e)
        ENGINE_STATE["step"] = "Initialization Error"
        ENGINE_STATE["details"] = str(e)
    finally:
        init_event.set()

@app.get("/api/status")
def get_engine_status():
    return ENGINE_STATE

import sqlite3
import contextlib

class StandaloneChatStore:
    def __init__(self, db_path: Path):
        self.db_path = db_path
        self._lock = threading.RLock()
        self._init_db()

    @contextlib.contextmanager
    def _connection(self):
        conn = sqlite3.connect(str(self.db_path), timeout=10.0, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL;")
        conn.execute("PRAGMA synchronous=NORMAL;")
        conn.execute("PRAGMA foreign_keys=ON;")
        try:
            yield conn
        finally:
            try:
                conn.close()
            except Exception:
                pass

    def _init_db(self):
        with self._lock, self._connection() as conn:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS conversations (
                    id TEXT PRIMARY KEY,
                    session_id TEXT NOT NULL,
                    title TEXT NOT NULL,
                    created_at REAL NOT NULL,
                    updated_at REAL NOT NULL
                );
                CREATE TABLE IF NOT EXISTS messages (
                    id TEXT PRIMARY KEY,
                    conversation_id TEXT NOT NULL,
                    role TEXT NOT NULL,
                    content TEXT NOT NULL,
                    image_url TEXT,
                    grounding_metadata TEXT,
                    created_at REAL NOT NULL,
                    FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS idx_conv_updated ON conversations(updated_at DESC);
                CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id);
            """)
            conn.commit()

    def generate_smart_title(self, first_message: str) -> str:
        clean = re.sub(r'\\[Context:[^\\]]*\\]', '', first_message or '').strip()
        clean = re.sub(r'\\s+', ' ', clean)
        if not clean:
            return "New Chat"
        if len(clean) > 40:
            return clean[:37].rstrip() + "..."
        return clean

    def create_conversation(self, title: str = "New Chat") -> dict:
        conv_id = f"conv_{{uuid.uuid4().hex[:12]}}"
        now = time.time()
        with self._lock, self._connection() as conn:
            conn.execute(
                "INSERT INTO conversations (id, session_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
                (conv_id, "standalone", title.strip() or "New Chat", now, now)
            )
            conn.commit()
        return {{"id": conv_id, "title": title.strip() or "New Chat", "created_at": now, "updated_at": now, "message_count": 0}}

    def list_conversations(self) -> list:
        with self._lock, self._connection() as conn:
            rows = conn.execute("""
                SELECT c.id, c.title, c.created_at, c.updated_at, COUNT(m.id) AS message_count
                FROM conversations c
                LEFT JOIN messages m ON m.conversation_id = c.id
                GROUP BY c.id
                ORDER BY c.updated_at DESC
            """).fetchall()
            return [dict(r) for r in rows]

    def get_conversation(self, conv_id: str) -> Optional[dict]:
        with self._lock, self._connection() as conn:
            row = conn.execute("SELECT id, title, created_at, updated_at FROM conversations WHERE id = ?", (conv_id,)).fetchone()
            if not row:
                return None
            msgs = conn.execute("SELECT id, role, content, image_url, grounding_metadata, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at ASC", (conv_id,)).fetchall()
            parsed_msgs = []
            for m in msgs:
                d = dict(m)
                if d.get("grounding_metadata"):
                    try:
                        import json
                        d["grounding_metadata"] = json.loads(d["grounding_metadata"])
                    except Exception:
                        pass
                parsed_msgs.append(d)
            res = dict(row)
            res["messages"] = parsed_msgs
            return res

    def delete_conversation(self, conv_id: str) -> bool:
        with self._lock, self._connection() as conn:
            conn.execute("DELETE FROM messages WHERE conversation_id = ?", (conv_id,))
            cur = conn.execute("DELETE FROM conversations WHERE id = ?", (conv_id,))
            conn.commit()
            return cur.rowcount > 0

    def add_message(self, conv_id: str, role: str, content: str, image_url: Optional[str] = None, grounding_metadata: Any = None) -> dict:
        msg_id = f"msg_{{uuid.uuid4().hex[:12]}}"
        now = time.time()
        import json
        meta_str = json.dumps(grounding_metadata) if grounding_metadata is not None else None
        with self._lock, self._connection() as conn:
            conn.execute(
                "INSERT INTO messages (id, conversation_id, role, content, image_url, grounding_metadata, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (msg_id, conv_id, role, content, image_url, meta_str, now)
            )
            conn.execute("UPDATE conversations SET updated_at = ? WHERE id = ?", (now, conv_id))
            conn.commit()
        return {{"id": msg_id, "conversation_id": conv_id, "role": role, "content": content, "created_at": now}}

chat_store = StandaloneChatStore(CHAT_DB_PATH)

@app.get("/api/conversations")
def list_conversations():
    return {{"conversations": chat_store.list_conversations()}}

@app.post("/api/conversations")
def create_conversation(req: Optional[dict] = None):
    title = (req or {{}}).get("title", "New Chat") if isinstance(req, dict) else "New Chat"
    return chat_store.create_conversation(title=title)

@app.get("/api/conversations/{{conv_id}}")
def get_conversation(conv_id: str):
    conv = chat_store.get_conversation(conv_id)
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")
    return conv

@app.delete("/api/conversations/{{conv_id}}")
def delete_conversation(conv_id: str):
    return {{"success": chat_store.delete_conversation(conv_id)}}

# Server-side conversation memory buffer
SERVER_MEMORY = []

class KeyTestRequest(BaseModel):
    provider: str
    api_key: Optional[str] = None
    model: Optional[str] = None

class MultiProviderDispatcher:
    DEFAULT_MODELS = {{
        "ollama": "llama3.2:3b",
        "openai": "gpt-4o-mini",
        "gemini": "gemini-1.5-flash",
        "openrouter": "deepseek/deepseek-r1",
        "groq": "llama-3.3-70b-versatile",
        "anthropic": "claude-3-5-haiku-20241022"
    }}

    @classmethod
    def test_key(cls, provider: str, api_key: str, model: Optional[str] = None) -> dict:
        provider = (provider or "ollama").lower().strip()
        api_key = (api_key or "").strip()

        if provider == "ollama":
            try:
                with httpx.Client(timeout=3.0) as client:
                    res = client.get("http://localhost:11434/api/tags")
                    if res.status_code == 200:
                        return {{"valid": True, "message": "Ollama local engine is online and connected."}}
                    return {{"valid": False, "message": f"Ollama returned status {{res.status_code}}."}}
            except Exception as e:
                return {{"valid": False, "message": f"Could not reach Ollama: {{str(e)}}"}}

        if not api_key:
            return {{"valid": False, "message": f"API key for {{provider}} cannot be empty."}}

        target_model = model or cls.DEFAULT_MODELS.get(provider, "gpt-4o-mini")

        try:
            with httpx.Client(timeout=10.0) as client:
                if provider == "openai":
                    res = client.post(
                        "https://api.openai.com/v1/chat/completions",
                        headers={{"Authorization": f"Bearer {{api_key}}", "Content-Type": "application/json"}},
                        json={{"model": target_model, "messages": [{{"role": "user", "content": "ping"}}], "max_tokens": 5}}
                    )
                elif provider == "openrouter":
                    res = client.post(
                        "https://openrouter.ai/api/v1/chat/completions",
                        headers={{"Authorization": f"Bearer {{api_key}}", "Content-Type": "application/json", "HTTP-Referer": "https://mirag.me", "X-Title": "Mi:RAG"}},
                        json={{"model": target_model, "messages": [{{"role": "user", "content": "ping"}}], "max_tokens": 5}}
                    )
                elif provider == "groq":
                    res = client.post(
                        "https://api.groq.com/openai/v1/chat/completions",
                        headers={{"Authorization": f"Bearer {{api_key}}", "Content-Type": "application/json"}},
                        json={{"model": target_model, "messages": [{{"role": "user", "content": "ping"}}], "max_tokens": 5}}
                    )
                elif provider == "gemini":
                    clean_m = target_model.replace("models/", "")
                    res = client.post(
                        f"https://generativelanguage.googleapis.com/v1beta/models/{{clean_m}}:generateContent?key={{api_key}}",
                        headers={{"Content-Type": "application/json"}},
                        json={{"contents": [{{"parts": [{{"text": "ping"}}]}}], "generationConfig": {{"maxOutputTokens": 5}}}}
                    )
                elif provider == "anthropic":
                    res = client.post(
                        "https://api.anthropic.com/v1/messages",
                        headers={{"x-api-key": api_key, "anthropic-version": "2023-06-01", "Content-Type": "application/json"}},
                        json={{"model": target_model, "max_tokens": 5, "messages": [{{"role": "user", "content": "ping"}}]}}
                    )
                else:
                    return {{"valid": False, "message": f"Unsupported provider '{{provider}}'."}}

                if res.status_code in [200, 201]:
                    return {{"valid": True, "message": f"Valid API Key! Successfully connected to {{provider.upper()}} ({{target_model}})."}}
                else:
                    return {{"valid": False, "message": f"{{provider.upper()}} error ({{res.status_code}}): {{res.text[:150]}}"}}
        except Exception as e:
            return {{"valid": False, "message": f"Connection error: {{str(e)}}"}}

    @classmethod
    def generate(cls, user_prompt: str, system_prompt: str, provider: str, model: str, api_key: Optional[str] = None) -> str:
        provider = (provider or "ollama").lower().strip()
        model_name = model or cls.DEFAULT_MODELS.get(provider, "llama3.2:3b")

        if provider == "ollama" or not api_key:
            with httpx.Client(timeout=90.0) as client:
                res = client.post(
                    "http://localhost:11434/api/chat",
                    json={{
                        "model": model_name,
                        "messages": [{{"role": "system", "content": system_prompt}}, {{"role": "user", "content": user_prompt}}],
                        "stream": False,
                        "options": {{"temperature": 0.1}}
                    }}
                )
                res.raise_for_status()
                return res.json().get("message", {{}}).get("content", "").strip()

        if provider == "openai":
            with httpx.Client(timeout=90.0) as client:
                res = client.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers={{"Authorization": f"Bearer {{api_key}}", "Content-Type": "application/json"}},
                    json={{"model": model_name, "messages": [{{"role": "system", "content": system_prompt}}, {{"role": "user", "content": user_prompt}}], "temperature": 0.1}}
                )
                res.raise_for_status()
                return res.json()["choices"][0]["message"]["content"].strip()

        if provider == "openrouter":
            with httpx.Client(timeout=90.0) as client:
                res = client.post(
                    "https://openrouter.ai/api/v1/chat/completions",
                    headers={{"Authorization": f"Bearer {{api_key}}", "Content-Type": "application/json", "HTTP-Referer": "https://mirag.me", "X-Title": "Mi:RAG"}},
                    json={{"model": model_name, "messages": [{{"role": "system", "content": system_prompt}}, {{"role": "user", "content": user_prompt}}], "temperature": 0.1}}
                )
                res.raise_for_status()
                return res.json()["choices"][0]["message"]["content"].strip()

        if provider == "groq":
            with httpx.Client(timeout=90.0) as client:
                res = client.post(
                    "https://api.groq.com/openai/v1/chat/completions",
                    headers={{"Authorization": f"Bearer {{api_key}}", "Content-Type": "application/json"}},
                    json={{"model": model_name, "messages": [{{"role": "system", "content": system_prompt}}, {{"role": "user", "content": user_prompt}}], "temperature": 0.1}}
                )
                res.raise_for_status()
                return res.json()["choices"][0]["message"]["content"].strip()

        if provider == "gemini":
            with httpx.Client(timeout=90.0) as client:
                clean_m = model_name.replace("models/", "")
                full_text = f"System Instructions:\\n{{system_prompt}}\\n\\nUser Question:\\n{{user_prompt}}" if system_prompt else user_prompt
                res = client.post(
                    f"https://generativelanguage.googleapis.com/v1beta/models/{{clean_m}}:generateContent?key={{api_key}}",
                    headers={{"Content-Type": "application/json"}},
                    json={{"contents": [{{"parts": [{{"text": full_text}}]}}], "generationConfig": {{"temperature": 0.1}}}}
                )
                res.raise_for_status()
                data = res.json()
                candidates = data.get("candidates", [])
                if candidates and "content" in candidates[0]:
                    return "".join(p.get("text", "") for p in candidates[0]["content"].get("parts", [])).strip()
                return "Gemini returned empty response."

        if provider == "anthropic":
            with httpx.Client(timeout=90.0) as client:
                payload = {{"model": model_name, "max_tokens": 4096, "temperature": 0.1, "system": system_prompt, "messages": [{{"role": "user", "content": user_prompt}}]}}
                res = client.post(
                    "https://api.anthropic.com/v1/messages",
                    headers={{"x-api-key": api_key, "anthropic-version": "2023-06-01", "Content-Type": "application/json"}},
                    json=payload
                )
                res.raise_for_status()
                data = res.json()
                return "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text").strip()

        raise ValueError(f"Unknown provider {{provider}}")

class ChatRequest(BaseModel):
    message: str
    top_k: Optional[int] = 6
    history: Optional[List[Dict[str, Any]]] = None
    provider: Optional[str] = "ollama"
    model: Optional[str] = None
    api_key: Optional[str] = None
    conversation_id: Optional[str] = None

class Citation(BaseModel):
    source_file: str
    relevance: float
    text: str

class ImageMatch(BaseModel):
    url: str
    filename: str
    source_file: str
    relevance: float

class ChatResponse(BaseModel):
    answer: str
    confidence_score: float
    is_grounded: bool
    citations: List[Citation]
    images: List[ImageMatch]
    query_image_url: Optional[str] = None
    conversation_id: Optional[str] = None

def apply_attention_reranking(query: str, raw_chunks: list, history: list) -> list:
    """Attention-weighted context reranking using query overlap and conversation focus."""
    query_words = set(re.findall(r"\\b\\w{{3,}}\\b", query.lower()))
    history_words = set()
    if history:
        for turn in history[-2:]:
            history_words.update(re.findall(r"\\b\\w{{3,}}\\b", str(turn.get("content", "")).lower()))

    scored = []
    for chunk in raw_chunks:
        text_lower = chunk["text"].lower()
        base_sim = chunk["score"]
        
        q_overlap = sum(1 for w in query_words if w in text_lower)
        q_boost = min(0.35, (q_overlap / max(1, len(query_words))) * 0.35)

        h_overlap = sum(1 for w in history_words if w in text_lower)
        h_boost = min(0.15, (h_overlap / max(1, len(history_words))) * 0.15) if history_words else 0.0

        diag_boost = 0.05 if "[DIAGRAM" in chunk["text"] else 0.0
        att_score = base_sim + q_boost + h_boost + diag_boost
        scored.append((att_score, chunk))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [c for _, c in scored]

def extract_relevant_images(query: str, chunks: list, is_image_query: bool = False) -> list:
    visual_keywords = ["diagram", "figure", "chart", "plot", "graph", "architecture", "image", "photo", "show me", "table", "visual", "fig.", "fig "]
    explicit_visual = any(kw in query.lower() for kw in visual_keywords)

    if not is_image_query and not explicit_visual:
        has_high_diag = any("[DIAGRAM" in c["text"] and c["score"] >= 0.45 for c in chunks)
        if not has_high_diag:
            return []

    matched = []
    seen = set()
    for c in chunks:
        meta_url = c["metadata"].get("image_url", "").strip() if isinstance(c["metadata"], dict) else ""
        urls = [meta_url] if meta_url else []
        found = re.findall(r"\\[Image URL:\\s*(.*?)\\]", c["text"])
        urls.extend([u.strip() for u in found if u.strip()])

        for u in urls:
            if u and u not in seen:
                if "_page_" in u.lower() and not is_image_query and not explicit_visual:
                    continue
                seen.add(u)
                fname = Path(u).name
                served_url = f"/images/{{fname}}"
                p_num = c["metadata"].get("page_number", "") if isinstance(c["metadata"], dict) else ""
                caption = f"{{c['source_file']}}" + (f" (Page {{p_num}})" if p_num else "")
                matched.append(ImageMatch(
                    url=served_url,
                    filename=fname,
                    source_file=caption,
                    relevance=round(c["score"] * 100, 1)
                ))
                if len(matched) >= (3 if is_image_query else 2):
                    break
        if len(matched) >= (3 if is_image_query else 2):
            break
    return matched

@app.get("/api/info")
def get_info():
    return {{
        "model_name": MODEL_NAME,
        "embedding_model": EMBEDDING_MODEL,
        "indexed_files": INDEXED_FILES,
        "status": "online"
    }}

@app.post("/api/clear_memory")
def clear_memory():
    global SERVER_MEMORY
    SERVER_MEMORY = []
    return {{"status": "success", "message": "Memory cleared."}}

@app.post("/api/models/fetch")
def fetch_provider_models(req: KeyTestRequest):
    provider = (req.provider or "ollama").lower().strip()
    api_key = (req.api_key or "").strip()
    
    if provider == "ollama":
        try:
            with httpx.Client(timeout=3.5) as client:
                res = client.get("http://localhost:11434/api/tags")
                if res.status_code == 200:
                    models = [m.get("name") for m in res.json().get("models", []) if m.get("name")]
                    if models:
                        return {{"provider": provider, "models": list(dict.fromkeys(models + ["qwen3.8-flash-next", "glm-5.3", "ornith-1.5", "granite4.2"]))}}
        except Exception:
            pass
        return {{"provider": provider, "models": ["qwen3.8-flash-next", "glm-5.3", "glm-5.3-flash", "ornith-1.5", "granite4.2", "qwen3.6", "deepseek-v4-flash", "llama3.2:3b", "llama3.2:1b", "qwen2.5:3b", "qwen2.5:7b", "mistral:latest"]}}

    if provider == "openai":
        if api_key:
            try:
                with httpx.Client(timeout=5.0) as client:
                    res = client.get("https://api.openai.com/v1/models", headers={{"Authorization": f"Bearer {{api_key}}"}})
                    if res.status_code == 200:
                        ids = [m.get("id") for m in res.json().get("data", []) if m.get("id")]
                        chat_models = [m for m in ids if any(k in m for k in ["gpt-5", "gpt-4", "gpt-3.5", "o1", "o3", "o4", "chatgpt"]) and not any(ex in m for ex in ["audio", "realtime", "tts", "search", "embedding", "whisper"])]
                        if chat_models:
                            return {{"provider": provider, "models": sorted(chat_models, reverse=True)}}
            except Exception:
                pass
        return {{"provider": provider, "models": ["gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.5", "gpt-5.5-pro", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.3-codex", "gpt-5.2", "gpt-4o", "gpt-4o-mini", "o3-mini"]}}

    if provider == "gemini":
        if api_key:
            try:
                with httpx.Client(timeout=5.0) as client:
                    res = client.get(f"https://generativelanguage.googleapis.com/v1beta/models?key={{api_key}}")
                    if res.status_code == 200:
                        gem_models = [m.get("name", "").replace("models/", "") for m in res.json().get("models", []) if "generateContent" in m.get("supportedGenerationMethods", [])]
                        if gem_models:
                            return {{"provider": provider, "models": gem_models}}
            except Exception:
                pass
        return {{"provider": provider, "models": ["gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.5-flash-cyber", "gemini-3.1-pro", "gemini-3-deep-think", "gemini-omni", "gemini-omni-1.1-flash", "gemini-2.0-flash"]}}

    if provider == "anthropic":
        return {{"provider": provider, "models": ["claude-fable-5", "claude-opus-5", "claude-sonnet-5", "claude-mythos-5", "claude-opus-4.8", "claude-sonnet-4.6", "claude-opus-4.7", "claude-opus-4.6", "claude-haiku-4.5"]}}

    if provider == "grok":
        if api_key:
            try:
                with httpx.Client(timeout=5.0) as client:
                    res = client.get("https://api.x.ai/v1/models", headers={{"Authorization": f"Bearer {{api_key}}"}})
                    if res.status_code == 200:
                        g_models = [m.get("id") for m in res.json().get("data", []) if m.get("id")]
                        if g_models:
                            return {{"provider": provider, "models": g_models}}
            except Exception:
                pass
        return {{"provider": provider, "models": ["grok-4.6", "grok-4.5", "grok-4", "grok-4.1", "grok-beta", "grok-vision-beta"]}}

    if provider == "openrouter":
        try:
            headers = {{"Authorization": f"Bearer {{api_key}}"}} if api_key else {{}}
            with httpx.Client(timeout=5.5) as client:
                res = client.get("https://openrouter.ai/api/v1/models", headers=headers)
                if res.status_code == 200:
                    or_models = [m.get("id") for m in res.json().get("data", []) if m.get("id")]
                    filtered = [m for m in or_models if any(kw in m.lower() for kw in ["gpt-5", "claude-", "opus-5", "sonnet-5", "gemini-3", "grok-4", "deepseek-v4", "glm-5", "minimax", "nemotron", "deepseek-r1", "llama-3"])]
                    if filtered:
                        return {{"provider": provider, "models": filtered[:50]}}
        except Exception:
            pass
        return {{"provider": provider, "models": ["openrouter/auto", "openai/gpt-5.6-sol", "anthropic/claude-opus-5", "anthropic/claude-sonnet-5", "google/gemini-3.7-flash", "x-ai/grok-4.6", "deepseek/deepseek-v4-flash", "z-ai/glm-5.3", "minimax/minimax-m3", "nvidia/nemotron-3-ultra", "deepseek/deepseek-r1", "meta-llama/llama-3.3-70b-instruct"]}}

    return {{"provider": provider, "models": ["qwen3.8-flash-next"]}}

@app.post("/api/chat", response_model=ChatResponse)
async def chat_rag(request: Request):
    global SERVER_MEMORY
    content_type = request.headers.get("content-type", "")
    query_image_path = None
    query_image_url = None
    user_message = ""
    client_history = None
    top_k = 6
    provider = "ollama"
    model = None
    api_key = None
    conversation_id = None

    if "application/json" in content_type:
        try:
            data = await request.json()
            user_message = data.get("message", "")
            top_k = int(data.get("top_k", 6))
            client_history = data.get("history", None)
            provider = str(data.get("provider", "ollama")).strip()
            model = data.get("model", None)
            api_key = data.get("api_key", None)
            conversation_id = data.get("conversation_id", None)
        except Exception:
            pass
    else:
        form = await request.form()
        user_message = str(form.get("message", "")).strip()
        provider = str(form.get("provider", "ollama")).strip()
        model = form.get("model", None)
        api_key = form.get("api_key", None)
        conversation_id = form.get("conversation_id", None)
        try:
            top_k = int(form.get("top_k", 6))
        except Exception:
            top_k = 6
        
        hist_raw = form.get("history")
        if hist_raw:
            try:
                import json
                client_history = json.loads(hist_raw)
            except Exception:
                pass

        uploaded_image = form.get("image")
        if uploaded_image and hasattr(uploaded_image, "filename") and uploaded_image.filename:
            fname = f"query_{{uuid.uuid4().hex[:8]}}_{{uploaded_image.filename}}"
            query_image_path = IMAGES_DIR / fname
            with open(query_image_path, "wb") as buffer:
                shutil.copyfileobj(uploaded_image.file, buffer)
            query_image_url = f"/images/{{fname}}"

    if not conversation_id:
        title = chat_store.generate_smart_title(user_message or "New Chat")
        conv = chat_store.create_conversation(title=title)
        conversation_id = conv["id"]

    if user_message or query_image_url:
        chat_store.add_message(
            conv_id=conversation_id,
            role="user",
            content=user_message or "[Visual Search]",
            image_url=query_image_url
        )

    effective_history = client_history if client_history is not None else SERVER_MEMORY

    if not user_message and not query_image_path:
        return ChatResponse(answer="Please enter a question or attach an image.", confidence_score=1.0, is_grounded=True, citations=[], images=[], conversation_id=conversation_id)

    global embedder, collection, ENGINE_STATE, init_event
    if not ENGINE_STATE.get("ready"):
        init_event.wait(timeout=25.0)

    if embedder is None or collection is None:
        return ChatResponse(
            answer="The AI inference engine is still initializing its vector weights. Please wait a few moments and try again.",
            confidence_score=0.0,
            is_grounded=False,
            citations=[],
            images=[],
            query_image_url=query_image_url,
            conversation_id=conversation_id
        )

    query_vec = embedder.encode(user_message or "multimodal image analysis", convert_to_numpy=True).tolist()
    results = collection.query(query_embeddings=[query_vec], n_results=top_k, include=["documents", "metadatas", "distances"])

    raw_chunks = []
    if results["ids"] and len(results["ids"][0]) > 0:
        for i in range(len(results["ids"][0])):
            dist = results["distances"][0][i]
            sim = max(0.0, 1.0 - dist)
            if sim >= 0.35:
                raw_chunks.append({{
                    "text": results["documents"][0][i],
                    "metadata": results["metadatas"][0][i],
                    "source_file": results["metadatas"][0][i].get("source_file", "Document"),
                    "score": sim
                }})

    if not raw_chunks:
        return ChatResponse(
            answer=f"I could not find any information about '{{user_message}}' in the pre-indexed documents. Please ask a question related to your indexed files.",
            confidence_score=0.0,
            is_grounded=False,
            citations=[],
            images=[],
            query_image_url=query_image_url
        )

    reranked_chunks = apply_attention_reranking(user_message, raw_chunks, effective_history)

    context_blocks = []
    unique_citations = {{}}
    for idx, c in enumerate(reranked_chunks[:5], start=1):
        raw_text = c['text']
        img_url = ""
        url_match = re.search(r'\\[Image URL:\\s*([^\\]]+)\\]', raw_text)
        if url_match:
            img_url = url_match.group(1).strip()
        clean_text = re.sub(r'\\[Image URL:\\s*[^\\]]+\\]', '', raw_text).strip()
        fig_inst = f"\\n[ATTACHED DIAGRAM AVAILABLE - Embed inline where discussed using: ![Figure from {{c['source_file']}}]({{img_url}})]" if img_url else ""
        context_blocks.append(f"--- DOCUMENT EXCERPT {{idx}} ({{c['source_file']}}) ---\\n{{clean_text}}{{fig_inst}}")
        score_pct = round(c["score"] * 100, 1)
        if c["source_file"] not in unique_citations or score_pct > unique_citations[c["source_file"]]["relevance"]:
            unique_citations[c["source_file"]] = {{
                "source_file": c["source_file"],
                "relevance": score_pct,
                "text": clean_text[:200] + "..." if len(clean_text) > 200 else clean_text
            }}

    history_block = ""
    if effective_history:
        turns = []
        for h in effective_history[-4:]:
            r = "User" if h.get("role") == "user" else "Assistant"
            turns.append(f"{{r}}: {{h.get('content', '')}}")
        if turns:
            history_block = "RECENT CONVERSATION MEMORY (PRIOR TURNS):\\n" + "\\n".join(turns) + "\\n\\n"

    system_prompt = (
        "You are a 100% private, local offline document intelligence engine.\\n"
        "1. Deliver a direct, finished, and well-structured answer in clean Markdown (use headers, bullet points, and tables).\\n"
        "2. CONTEXTUAL INLINE DIAGRAMS: When discussing a figure or diagram from the context, embed it inline right where discussed using: ![Caption](image_url).\\n"
        "3. DIRECTNESS & INTENT: Answer specifically what the user asks. If the user asks about a specific diagram, table, or concept, focus strictly on explaining that item. Do NOT reproduce a boilerplate paper template unless requested.\\n"
        "4. Use conversation memory to resolve pronouns and follow-up references.\\n"
        "5. Answer ONLY using the factual context provided. Do not hallucinate."
    )

    intent_hint = ""
    um_lower = (user_message or "").lower().strip()
    is_general_sum = any(k in um_lower for k in ["summary", "summarise", "overview", "what is this paper about"])
    if not is_general_sum and any(k in um_lower for k in ["diagram", "figure", "image", "chart", "table", "graph", "histogram", "architecture", "training", "model", "pipeline", "what is", "how does", "why"]):
        intent_hint = f"TARGETED FOCUS DIRECTIVE: The user specifically asks about: '{{user_message}}'. Address ONLY this topic directly without generating an unrequested general paper summary.\\n\\n"

    joined_context = "\\n\\n".join(context_blocks)
    user_prompt = (
        f"KNOWLEDGE BASE CONTEXT:\\n"
        f"{{joined_context}}\\n\\n"
        f"{{history_block}}"
        f"{{intent_hint}}"
        f"USER QUERY: {{user_message}}\\n\\n"
        f"FINISHED GROUNDED ANSWER:"
    )

    target_model = model or MODEL_NAME
    provider_name = (provider or "ollama").lower().strip()

    try:
        ans_text = MultiProviderDispatcher.generate(
            user_prompt=user_prompt,
            system_prompt=system_prompt,
            provider=provider_name,
            model=target_model,
            api_key=api_key
        )
    except Exception as e:
        ans_text = f"Error from {{provider_name.upper()}}: {{str(e)}}. Make sure your model/key settings are valid or local Ollama is active."

    ans_text = re.sub(r"(?i)(?:as an ai text model,\\s*)?(?:unfortunately,\\s*)?I (?:am|am currently)?\\s*(?:unable|not able)\\s*to (?:display|show|view) (?:the )?images? (?:directly|here)?[^.\\n]*[.\\n]?", "", ans_text)
    ans_text = re.sub(r"(?i)The image URL is\\s*.*?(?:/images/|/api/sessions/)\\S+", "", ans_text)

    matched_images = extract_relevant_images(user_message, reranked_chunks, is_image_query=bool(query_image_path))

    SERVER_MEMORY.append({{"role": "user", "content": user_message or "[Visual Search]"}})
    SERVER_MEMORY.append({{"role": "assistant", "content": ans_text}})
    if len(SERVER_MEMORY) > 12:
        SERVER_MEMORY = SERVER_MEMORY[-12:]

    avg_conf = sum(c["score"] for c in reranked_chunks) / len(reranked_chunks)

    chat_store.add_message(
        conv_id=conversation_id,
        role="assistant",
        content=ans_text,
        grounding_metadata=[dict(v) for v in unique_citations.values()]
    )

    return ChatResponse(
        answer=ans_text,
        confidence_score=round(avg_conf, 4),
        is_grounded=True,
        citations=[Citation(**v) for v in unique_citations.values()],
        images=matched_images,
        query_image_url=query_image_url,
        conversation_id=conversation_id
    )

@app.post("/api/keys/test")
def test_key(req: KeyTestRequest):
    return MultiProviderDispatcher.test_key(req.provider, req.api_key or "", req.model)

@app.get("/images/{{filename}}")
@app.get("/api/sessions/{{session_id}}/images/{{filename}}")
def serve_image(filename: str, session_id: Optional[str] = None):
    img_path = IMAGES_DIR / filename
    if img_path.exists():
        return FileResponse(str(img_path))
    for f in IMAGES_DIR.glob("*.*"):
        if f.name.lower() == filename.lower():
            return FileResponse(str(f))
    raise HTTPException(status_code=404, detail=f"Image {{filename}} not found")

@app.get("/", response_class=HTMLResponse)
def serve_ui():
    ui_path = Path("./index.html")
    if ui_path.exists():
        return ui_path.read_text(encoding="utf-8")
    return "<h1>Offline Enterprise RAG Ready</h1>"

@app.post("/api/clear_memory")
def clear_memory():
    global SERVER_MEMORY
    SERVER_MEMORY = []
    return {{"status": "ok", "message": "Conversation memory cleared."}}

@app.get("/api/health")
def health_check():
    return {{"status": "ok", "service": "Mi-RAG Turnkey Assistant"}}

@app.get("/api/info")
def get_info():
    return {{
        "model_name": MODEL_NAME,
        "indexed_files": INDEXED_FILES,
        "status": "Ready",
        "features": ["attention_reranking", "conversation_memory", "local_storage", "multimodal_search"]
    }}

@app.post("/api/shutdown")
def shutdown_server():
    def do_kill():
        import time, os, signal
        time.sleep(0.6)
        try:
            os.kill(os.getpid(), signal.SIGTERM)
        except Exception:
            os._exit(0)
    threading.Thread(target=do_kill).start()
    return {{"status": "ok", "message": "Server shutting down."}}

if __name__ == "__main__":
    import sys
    import os
    import socket
    import subprocess
    import threading
    import time
    import urllib.request
    import webbrowser
    from pathlib import Path

    port_file = Path(__file__).parent / ".port"

    def find_desktop_app_browser():
        candidates = [
            Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Google" / "Chrome" / "Application" / "chrome.exe",
            Path(os.environ.get("ProgramFiles(x86)", "C:/Program Files (x86)")) / "Google" / "Chrome" / "Application" / "chrome.exe",
            Path(os.environ.get("LOCALAPPDATA", "")) / "Google" / "Chrome" / "Application" / "chrome.exe",
            Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "BraveSoftware" / "Brave-Browser" / "Application" / "brave.exe",
            Path(os.environ.get("LOCALAPPDATA", "")) / "BraveSoftware" / "Brave-Browser" / "Application" / "brave.exe",
        ]
        return next((p for p in candidates if p and p.exists()), None)

    def launch_app_window(target_url):
        browser_exe = find_desktop_app_browser()
        user_data = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "Mi-RAG" / "AppProfile"
        user_data.mkdir(parents=True, exist_ok=True)
        if browser_exe:
            try:
                print(f"[*] Opening dedicated desktop app window: {{browser_exe}}")
                proc = subprocess.Popen([
                    str(browser_exe),
                    f"--app={{target_url}}",
                    "--window-size=1280,840",
                    f"--user-data-dir={{user_data}}",
                    "--no-first-run",
                    "--no-default-browser-check"
                ])
                def watch_proc(p):
                    try:
                        p.wait()
                        time.sleep(0.4)
                        os._exit(0)
                    except Exception:
                        pass
                threading.Thread(target=watch_proc, args=(proc,), daemon=True).start()
                return True
            except Exception as e:
                print(f"[!] Desktop window error: {{e}}")
        webbrowser.open(target_url)
        return False

    # Fast-check if an instance of this assistant is already running on this machine
    if port_file.exists():
        try:
            old_port = int(port_file.read_text(encoding="utf-8").strip())
            test_url = f"http://127.0.0.1:{{old_port}}"
            with urllib.request.urlopen(f"{{test_url}}/api/health", timeout=0.8) as resp:
                if resp.status == 200:
                    print(f"[*] Assistant is already running at {{test_url}}. Refocusing desktop window...")
                    launch_app_window(test_url)
                    sys.exit(0)
        except Exception:
            try:
                port_file.unlink(missing_ok=True)
            except Exception:
                pass

    # 1. Start loading vector DB & neural embedding weights in background
    init_thread = threading.Thread(target=init_engine_background, daemon=True)
    init_thread.start()

    def find_available_port(preferred=8000, max_tries=100):
        for p in range(preferred, preferred + max_tries):
            try:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.bind(('127.0.0.1', p))
                    return p
            except OSError:
                continue
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(('127.0.0.1', 0))
            return s.getsockname()[1]

    port = find_available_port(8000)
    url = f"http://127.0.0.1:{{port}}"
    print(f"[*] Starting Standalone Enterprise RAG Assistant on {{url}} (Model: {{MODEL_NAME}})...")

    # Save active port
    try:
        port_file.write_text(str(port), encoding="utf-8")
    except Exception:
        pass

    # 2. Open dedicated desktop app window as soon as FastAPI server is verified answering 200 OK
    def open_desktop_window_when_ready(target_url):
        t0 = time.time()
        while time.time() - t0 < 30.0:
            try:
                with urllib.request.urlopen(f"{{target_url}}/api/health", timeout=0.5) as res:
                    if res.status == 200:
                        break
            except Exception:
                pass
            time.sleep(0.12)
        launch_app_window(target_url)

    threading.Thread(target=open_desktop_window_when_ready, args=(url,), daemon=True).start()

    # 3. Run FastAPI / Uvicorn directly on the main thread so the server process NEVER terminates unexpectedly
    try:
        uvicorn.run(app, host="127.0.0.1", port=port, log_level="warning")
    except KeyboardInterrupt:
        print("\\n[*] Shutting down...")
    finally:
        try:
            port_file.unlink(missing_ok=True)
        except Exception:
            pass
'''

    def _generate_standalone_ui(self, model_name: str, session_id: str, indexed_files: list) -> str:
        desktop_template = Path("web/templates/desktop.html")
        if not desktop_template.exists():
            desktop_template = Path(__file__).parent.parent / "web" / "templates" / "desktop.html"
        if not desktop_template.exists():
            desktop_template = Path("web/templates/portal.html")
        if not desktop_template.exists():
            desktop_template = Path(__file__).parent.parent / "web" / "templates" / "portal.html"

        if desktop_template.exists():
            content = desktop_template.read_text(encoding="utf-8")
            clean_m = model_name.replace("ollama:", "").replace("local:", "")
            content = content.replace("Production Engine: Local Assistant", f"Production Engine: {clean_m}")
            content = content.replace("Production Engine: {{MODEL_NAME}}", f"Production Engine: {clean_m}")
            content = content.replace("{{SESSION_BADGE}}", f"Production Engine: {clean_m}")

            # Pre-render indexed documents with clean SVG icons (zero emojis)
            files_pills = "".join([
                f'<div class="doc-pill-item" title="{Path(f).name}">'
                f'<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
                f'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>'
                f'<polyline points="14 2 14 8 20 8"></polyline></svg>'
                f'<span>{Path(f).name}</span></div>'
                for f in indexed_files
            ]) or '<div class="doc-pill-item">Knowledge Base Documents</div>'

            content = content.replace(
                '<div style="font-size: 0.78rem; color: #64748b; padding: 0.4rem;">Knowledge Base Documents</div>',
                files_pills
            )
            content = content.replace(
                '<div style="font-size: 0.78rem; color: #64748b; padding: 0.4rem;">No documents in this session</div>',
                files_pills
            )
            content = content.replace('{{INDEXED_DOCUMENTS_PLACEHOLDER}}', files_pills)
            return content

        return f"<h1>Production RAG Assistant ({model_name})</h1>"

    def _generate_installer_script(self, model_name: str, embedding_model: str) -> str:
        short_name = model_name[:12]
        return f'''"""
Standalone Turnkey Pre-flight Check & Instant Setup
Auto-generated by Autonomous RAG Factory
"""
import sys
import os
import time
import json
import subprocess
import urllib.request
import urllib.error

def render_progress_bar(iteration, total, prefix="", suffix="", length=28, fill="█", empty="░"):
    if total <= 0:
        percent = 100.0
        filled_length = length
    else:
        percent = min(100.0, max(0.0, (iteration / float(total)) * 100.0))
        filled_length = int(length * iteration // total)
    bar = fill * filled_length + empty * (length - filled_length)
    sys.stdout.write(f"\\r  {{prefix}} [{{bar}}] {{percent:.1f}}% {{suffix}}")
    sys.stdout.flush()
    if iteration >= total and total > 0:
        sys.stdout.write("\\n")
        sys.stdout.flush()

def format_bytes(size_bytes):
    if not size_bytes or size_bytes <= 0:
        return "0 B"
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_bytes < 1024.0:
            return f"{{size_bytes:.1f}} {{unit}}"
        size_bytes /= 1024.0
    return f"{{size_bytes:.1f}} TB"

def check_environment():
    try:
        import fastapi
        import uvicorn
        import chromadb
        import sentence_transformers
        import httpx
        import torch
        return True
    except (ImportError, OSError, Exception):
        return False

def is_model_cached(model_str):
    try:
        req = urllib.request.Request("http://localhost:11434/api/tags")
        with urllib.request.urlopen(req, timeout=1.5) as res:
            if res.status == 200:
                data = json.loads(res.read().decode("utf-8"))
                models = [m.get("name", "").split(":")[0] for m in data.get("models", [])]
                models.extend([m.get("name", "") for m in data.get("models", [])])
                target_root = model_str.split(":")[0]
                return model_str in models or target_root in models
    except Exception:
        pass
    return False

env_ready = check_environment()
model_ready = is_model_cached("{model_name}")

if env_ready and model_ready:
    print("[*] Fast-start: All dependencies and local models are verified and cached.")
    sys.exit(0)

print("\\n" + "="*70)
print("       STANDALONE ENTERPRISE RAG - ONE-CLICK SETUP")
print("="*70)

if not env_ready:
    print("\\n[1/2] Installing Python dependencies (Streaming live progress)...")
    req_file = "requirements.txt"
    if os.path.exists(req_file):
        process = subprocess.Popen(
            [sys.executable, "-m", "pip", "install", "-r", req_file, "--progress-bar", "on"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
        
        start_time = time.time()
        for raw_line in process.stdout:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("Collecting"):
                pkg_name = line.replace("Collecting", "").strip().split()[0]
                sys.stdout.write(f"\\r  [Download] {{pkg_name:<35}}\\n")
                sys.stdout.flush()
            elif "Downloading" in line:
                sys.stdout.write(f"\\r    -> {{line[:60]:<60}}")
                sys.stdout.flush()
            elif line.startswith("Installing collected packages:"):
                sys.stdout.write(f"\\n  [Installing collected wheels...]\\n")
                sys.stdout.flush()
            elif line.startswith("Successfully installed"):
                sys.stdout.write(f"\\n  [OK] All dependencies configured in {{int(time.time() - start_time)}}s!\\n")
                sys.stdout.flush()
        process.wait()

        # Copy VC runtimes to torch/lib if available
        vc_dir = Path("./assets/vc_runtimes")
        if vc_dir.exists():
            try:
                import importlib.util
                torch_spec = importlib.util.find_spec("torch")
                if torch_spec and torch_spec.origin:
                    t_lib = Path(torch_spec.origin).parent / "lib"
                    if t_lib.exists():
                        for f in vc_dir.glob("*.dll"):
                            target_f = t_lib / f.name
                            if not target_f.exists():
                                shutil.copy2(f, target_f)
            except Exception:
                pass

        # Verify PyTorch loads without [WinError 1114]
        try:
            import torch
        except OSError as err:
            if "1114" in str(err) or "c10.dll" in str(err):
                print("  [*] PyTorch DLL initialization failed (WinError 1114). Switching to universal CPU release...")
                subprocess.run(
                    [sys.executable, "-m", "pip", "install", "--force-reinstall", "--no-cache-dir",
                     "torch", "torchvision", "--index-url", "https://download.pytorch.org/whl/cpu"],
                    check=False
                )
else:
    print("[1/2] [OK] Core dependencies verified!")

if not model_ready:
    print(f"\\n[2/2] Downloading Local LLM: {model_name}...")
    ollama_url = "http://localhost:11434"
    try:
        pull_req = urllib.request.Request(
            f"{{ollama_url}}/api/pull",
            data=json.dumps({{"name": "{model_name}", "stream": True}}).encode("utf-8"),
            headers={{"Content-Type": "application/json"}}
        )
        with urllib.request.urlopen(pull_req, timeout=600.0) as response:
            prev_completed = 0
            last_time = time.time()
            for line in response:
                if not line:
                    continue
                chunk = json.loads(line.decode("utf-8"))
                status = chunk.get("status", "working")
                total = chunk.get("total", 0)
                completed = chunk.get("completed", 0)

                if total > 0:
                    cur_time = time.time()
                    speed_str = ""
                    eta_str = ""
                    if completed > prev_completed and (cur_time - last_time) > 0.25:
                        bytes_per_sec = (completed - prev_completed) / (cur_time - last_time)
                        if bytes_per_sec > 0:
                            speed_str = f"• {{format_bytes(bytes_per_sec)}}/s"
                            rem_seconds = int((total - completed) / bytes_per_sec)
                            eta_str = f"• ETA: {{rem_seconds}}s"
                        prev_completed = completed
                        last_time = cur_time

                    render_progress_bar(
                        completed,
                        total,
                        prefix="{short_name:<12}",
                        suffix=f"({{format_bytes(completed)}} / {{format_bytes(total)}}) {{speed_str}} {{eta_str}}"
                    )
                else:
                    sys.stdout.write(f"\\r  [*] {{status:<45}}")
                    sys.stdout.flush()
        sys.stdout.write(f"\\r  [OK] Local LLM '{model_name}' is verified, cached, and ready!\\n")
    except Exception as e:
        print(f"  [*] Model status note: {{e}}")
else:
    print(f"[2/2] [OK] Model '{model_name}' is cached and ready!")

print("\\n[*] Starting Production Assistant on http://localhost:8000 ...\\n")
'''

    def _generate_install_guide(self, model_name: str) -> str:
        return f'''# Standalone Production RAG Assistant

This package contains your turnkey, fully-indexed RAG assistant with:
- **Direct Launch into Chat Playground (Bypasses Studio/Training screen completely)**
- **Pre-Indexed Vector Database (ChromaDB)**
- **Multi-Turn Conversation Memory & LocalStorage Persistence**
- **Attention-Weighted Reranking & Anti-Hallucination Guardrails**
- **Multimodal Visual Diagram Analysis & Image Search**
- **Instant 1-Click Launch (starts in <1s once cached)**

---

## 1-Click Launch (Windows)
1. Double-click **`run.bat`**.
2. Your browser will automatically open straight into the **Chat Playground** with all your documents and memory ready!

---

## Linux / macOS Launch
1. Make executable and run:
   ```bash
   chmod +x run.sh
   ./run.sh
   ```
2. Open the URL shown in the terminal in your browser.

---

## Docker Launch
```bash
docker compose up --build
```
'''

    def _build_windows_installer(self, bundle_dir: Path, session: RAGSession) -> Optional[Path]:
        """
        Compiles the turnkey standalone session into a single-file Windows setup executable (.exe)
        modeled after the DaVinci Resolve modern wizard installer.
        """
        setup_base_name = f"Mi-RAG_Setup_{session.session_id[:8]}"
        target_exe = self.output_dir / f"{setup_base_name}.exe"
        try:
            target_exe.unlink(missing_ok=True)
        except Exception:
            pass

        # 1. Locate iscc.exe
        iscc_candidates = [
            Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Inno Setup 6" / "iscc.exe",
            Path(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")) / "Inno Setup 6" / "iscc.exe",
            Path(os.environ.get("ProgramFiles", r"C:\Program Files")) / "Inno Setup 6" / "iscc.exe",
        ]
        which_iscc = shutil.which("iscc")
        if which_iscc:
            iscc_candidates.insert(0, Path(which_iscc))

        iscc_exe = next((p for p in iscc_candidates if p and p.exists()), None)
        if not iscc_exe:
            return None

        # 2. Copy Sciter DirectX engine & native launcher
        packager_bin = Path(__file__).parent / "bin"
        for bin_file in ["MiRAG.exe"]:
            src = packager_bin / bin_file
            if src.exists():
                self._safe_copy_file(src, bundle_dir / bin_file)

        # 3. Copy DaVinci Resolve style wizard sidebar & header bitmaps
        packager_assets = Path(__file__).parent / "assets"
        sidebar_bmp = bundle_dir / "wizard_sidebar.bmp"
        small_bmp = bundle_dir / "wizard_small.bmp"
        if (packager_assets / "wizard_sidebar.bmp").exists():
            self._safe_copy_file(packager_assets / "wizard_sidebar.bmp", sidebar_bmp)
        if (packager_assets / "wizard_small.bmp").exists():
            self._safe_copy_file(packager_assets / "wizard_small.bmp", small_bmp)

        # 4. Generate installer.iss
        icon_path = bundle_dir / "static" / "assets" / "favicon.ico"
        if not icon_path.exists():
            icon_path = Path("public/static/assets/favicon.ico").resolve()

        iss_content = f"""[Setup]
AppName=Mi-RAG Assistant
AppVersion=1.0.0
AppPublisher=Autonomous RAG Factory
AppPublisherURL=https://mirag.me
DefaultDirName={{localappdata}}\\Programs\\Mi-RAG
DefaultGroupName=Mi-RAG
AllowNoIcons=yes
OutputDir={self.output_dir.resolve()}
OutputBaseFilename={setup_base_name}
SetupIconFile={icon_path.resolve()}
WizardStyle=modern
WizardImageFile={sidebar_bmp.resolve()}
WizardSmallImageFile={small_bmp.resolve()}
Compression=lzma2/ultra64
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest
DisableWelcomePage=no

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: checkedonce
Name: "addtopath"; Description: "Add application directory to User &PATH environment variable"; GroupDescription: "System integration:"; Flags: unchecked

[Files]
Source: "{bundle_dir.resolve()}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{userdesktop}}\\Mi-RAG Assistant"; Filename: "{{app}}\\MiRAG.exe"; IconFilename: "{{app}}\\static\\assets\\favicon.ico"; Tasks: desktopicon
Name: "{{autoprograms}}\\Mi-RAG Assistant"; Filename: "{{app}}\\MiRAG.exe"; IconFilename: "{{app}}\\static\\assets\\favicon.ico"

[Registry]
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{{olddata}};{{app}}"; Tasks: addtopath; Check: NeedsAddPath(ExpandConstant('{{app}}'))

[Run]
Filename: "{{app}}\\MiRAG.exe"; Description: "Launch Mi-RAG Assistant now"; Flags: postinstall nowait skipifsilent

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + UpperCase(Param) + ';', ';' + UpperCase(OrigPath) + ';') = 0;
end;
"""
        iss_file = bundle_dir / "installer.iss"
        self._safe_write_text(iss_file, iss_content, encoding="utf-8")

        # 5. Compile with ISCC
        try:
            res = subprocess.run([str(iscc_exe), str(iss_file)], capture_output=True, text=True, timeout=120)
            target_exe = self.output_dir / f"{setup_base_name}.exe"
            if target_exe.exists() and target_exe.stat().st_size > 0:
                return target_exe
        except Exception:
            pass

        return None

    def create_package(self, session: RAGSession) -> Path:
        bundle_dir = session.session_dir / "standalone_bundle"
        bundle_dir.mkdir(parents=True, exist_ok=True)

        dest_db = bundle_dir / "vector_db"
        dest_db.mkdir(parents=True, exist_ok=True)
        for root, dirs, files in os.walk(session.db_dir):
            rel_path = Path(root).relative_to(session.db_dir)
            target_dir = dest_db / rel_path
            target_dir.mkdir(parents=True, exist_ok=True)
            for f in files:
                src_file = Path(root) / f
                dst_file = target_dir / f
                try:
                    if not dst_file.exists() or dst_file.stat().st_size != src_file.stat().st_size:
                        shutil.copy2(src_file, dst_file)
                except Exception:
                    pass

        # Copy SQLite chat history database so past conversations travel with download
        chat_db = session.session_dir / "chat_history.db"
        if chat_db.exists():
            try:
                shutil.copy2(chat_db, bundle_dir / "chat_history.db")
            except Exception:
                pass

        images_dest = bundle_dir / "images"
        images_dest.mkdir(parents=True, exist_ok=True)
        search_dirs = [
            getattr(session, "images_dir", None),
            getattr(session, "uploads_dir", None),
            session.session_dir / "images",
            session.session_dir / "extracted_images",
            session.session_dir / "uploads",
            session.session_dir
        ]
        for sdir in search_dirs:
            if sdir and Path(sdir).exists():
                for img_file in Path(sdir).glob("*.*"):
                    if img_file.is_file() and img_file.suffix.lower() in [".png", ".jpg", ".jpeg", ".webp", ".bmp"]:
                        target = images_dest / img_file.name
                        try:
                            if not target.exists() or target.stat().st_size != img_file.stat().st_size:
                                shutil.copy2(img_file, target)
                        except Exception:
                            pass

        # Copy static assets (logo, favicon, background) into bundle
        static_dest = bundle_dir / "static" / "assets"
        static_dest.mkdir(parents=True, exist_ok=True)
        source_assets = Path("public/static/assets")
        if not source_assets.exists():
            source_assets = Path(__file__).parent.parent / "public" / "static" / "assets"
        if source_assets.exists():
            for asset_file in source_assets.glob("*.*"):
                if asset_file.is_file():
                    self._safe_copy_file(asset_file, static_dest / asset_file.name)

        # Copy VC runtimes into bundle
        vc_source = Path("assets/vc_runtimes")
        if not vc_source.exists():
            vc_source = Path(__file__).parent.parent / "assets" / "vc_runtimes"
        if vc_source.exists():
            vc_dest = bundle_dir / "assets" / "vc_runtimes"
            vc_dest.mkdir(parents=True, exist_ok=True)
            for dll_file in vc_source.glob("*.dll"):
                self._safe_copy_file(dll_file, vc_dest / dll_file.name)
                self._safe_copy_file(dll_file, bundle_dir / dll_file.name)

        # Write Standalone Server, Hydrated Direct Chat UI & Installer
        embed_model = getattr(session, "embedding_model", "BAAI/bge-base-en-v1.5")
        self._safe_write_text(
            bundle_dir / "server.py",
            self._generate_standalone_server_code(session.model_name, embed_model, session.indexed_files),
            encoding="utf-8"
        )
        self._safe_write_text(
            bundle_dir / "index.html",
            self._generate_standalone_ui(session.model_name, session.session_id, session.indexed_files),
            encoding="utf-8"
        )
        self._safe_write_text(
            bundle_dir / "setup.py",
            self._generate_installer_script(session.model_name, embed_model),
            encoding="utf-8"
        )

        requirements_txt = (
            "fastapi>=0.110.0\n"
            "uvicorn>=0.28.0\n"
            "pydantic>=2.6.0\n"
            "chromadb>=0.4.24\n"
            "sentence-transformers>=2.6.0\n"
            "httpx>=0.27.0\n"
            "python-multipart>=0.0.9\n"
        )
        self._safe_write_text(bundle_dir / "requirements.txt", requirements_txt, encoding="utf-8")

        # Write start.bat and run.bat (Windows Frictionless Local Launchers)
        launcher_bat = (
            "@echo off\r\n"
            "setlocal enabledelayedexpansion\r\n"
            "cd /d \"%~dp0\"\r\n"
            "title Standalone Enterprise RAG Assistant\r\n"
            "\r\n"
            "echo =========================================================\r\n"
            "echo   Standalone Enterprise RAG Assistant\r\n"
            "echo =========================================================\r\n"
            "\r\n"
            ":: 0. Ensure relative local directories exist\r\n"
            "if not exist logs mkdir logs\r\n"
            "if not exist images mkdir images\r\n"
            "if not exist vector_db mkdir vector_db\r\n"
            "\r\n"
            ":: 1. Deploy local VC++ runtime DLLs if bundled\r\n"
            "if exist \"assets\\vc_runtimes\\*.dll\" (\r\n"
            "    copy /y \"assets\\vc_runtimes\\*.dll\" . >nul 2>&1\r\n"
            "    if exist \".venv\\Lib\\site-packages\\torch\\lib\" (\r\n"
            "        copy /y \"assets\\vc_runtimes\\*.dll\" \".venv\\Lib\\site-packages\\torch\\lib\" >nul 2>&1\r\n"
            "    )\r\n"
            ")\r\n"
            "\r\n"
            ":: 2. If dedicated local environment exists, use it immediately\r\n"
            "if exist \".venv\\Scripts\\python.exe\" (\r\n"
            "    echo [*] Launching using local environment (.venv)...\r\n"
            "    .venv\\Scripts\\python.exe server.py\r\n"
            "    if !errorlevel! neq 0 (\r\n"
            "        echo.\r\n"
            "        echo =========================================================\r\n"
            "        echo  [!] Server exited with an error code (!errorlevel!).\r\n"
            "        echo  [i] Check logs\\server.log for details.\r\n"
            "        echo =========================================================\r\n"
            "    ) else (\r\n"
            "        echo.\r\n"
            "        echo =========================================================\r\n"
            "        echo  [i] Standalone Assistant session finished.\r\n"
            "        echo =========================================================\r\n"
            "    )\r\n"
            "    pause\r\n"
            "    exit /b\r\n"
            ")\r\n"
            "\r\n"
            ":: 3. Find available Python on machine\r\n"
            "set \"PY_CMD=\"\r\n"
            "where python >nul 2>&1\r\n"
            "if !errorlevel! equ 0 (\r\n"
            "    set \"PY_CMD=python\"\r\n"
            ") else (\r\n"
            "    where py >nul 2>&1\r\n"
            "    if !errorlevel! equ 0 (\r\n"
            "        set \"PY_CMD=py\"\r\n"
            "    )\r\n"
            ")\r\n"
            "\r\n"
            "if \"!PY_CMD!\"==\"\" (\r\n"
            "    echo.\r\n"
            "    echo =========================================================\r\n"
            "    echo  [!] Python 3.10+ was not found on your system PATH.\r\n"
            "    echo =========================================================\r\n"
            "    echo  Please install Python from https://www.python.org/downloads/\r\n"
            "    echo  Ensure 'Add Python to PATH' is checked during setup.\r\n"
            "    echo.\r\n"
            "    pause\r\n"
            "    exit /b 1\r\n"
            ")\r\n"
            "\r\n"
            ":: 4. Fast check if existing python environment has all needed libraries\r\n"
            "\"!PY_CMD!\" -c \"import fastapi, chromadb, sentence_transformers, httpx, uvicorn\" 2>nul\r\n"
            "if !errorlevel! equ 0 (\r\n"
            "    echo [*] Launching Standalone Assistant...\r\n"
            "    \"!PY_CMD!\" server.py\r\n"
            "    if !errorlevel! neq 0 (\r\n"
            "        echo.\r\n"
            "        echo =========================================================\r\n"
            "        echo  [!] Server exited with an error code (!errorlevel!).\r\n"
            "        echo  [i] Check logs\\server.log for details.\r\n"
            "        echo =========================================================\r\n"
            "    ) else (\r\n"
            "        echo.\r\n"
            "        echo =========================================================\r\n"
            "        echo  [i] Standalone Assistant session finished.\r\n"
            "        echo =========================================================\r\n"
            "    )\r\n"
            "    pause\r\n"
            "    exit /b\r\n"
            ")\r\n"
            "\r\n"
            ":: 5. Otherwise setup self-contained local virtual environment\r\n"
            "echo [*] Initializing local environment (.venv)...\r\n"
            "\"!PY_CMD!\" -m venv --system-site-packages .venv\r\n"
            "if not exist \".venv\\Scripts\\python.exe\" (\r\n"
            "    echo [!] Failed to create local virtual environment.\r\n"
            "    pause\r\n"
            "    exit /b 1\r\n"
            ")\r\n"
            "\r\n"
            "echo [*] Installing required packages into local environment...\r\n"
            ".venv\\Scripts\\python.exe -m pip install -r requirements.txt --no-warn-script-location\r\n"
            "if !errorlevel! neq 0 (\r\n"
            "    echo [!] Note: Some packages finished with warnings. Launching Assistant...\r\n"
            ")\r\n"
            "\r\n"
            "echo [*] Launching Standalone Assistant...\r\n"
            ".venv\\Scripts\\python.exe server.py\r\n"
            "if !errorlevel! neq 0 (\r\n"
            "    echo.\r\n"
            "    echo =========================================================\r\n"
            "    echo  [!] Server exited with an error code (!errorlevel!).\r\n"
            "    echo  [i] Check logs\\server.log for details.\r\n"
            "    echo =========================================================\r\n"
            ") else (\r\n"
            "    echo.\r\n"
            "    echo =========================================================\r\n"
            "    echo  [i] Standalone Assistant session finished.\r\n"
            "    echo =========================================================\r\n"
            ")\r\n"
            "pause\r\n"
        )
        self._safe_write_text(bundle_dir / "start.bat", launcher_bat, encoding="utf-8")
        self._safe_write_text(bundle_dir / "run.bat", launcher_bat, encoding="utf-8")

        # Write start.sh and run.sh (Linux/Mac Launchers)
        launcher_sh = (
            "#!/usr/bin/env bash\n"
            "set -e\n"
            "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n"
            "cd \"$SCRIPT_DIR\"\n"
            "mkdir -p logs images vector_db\n"
            "echo \"=========================================================\"\n"
            "echo \"  Standalone Enterprise RAG Assistant\"\n"
            "echo \"=========================================================\"\n"
            "if [ -f \".venv/bin/python\" ]; then\n"
            "    echo \"[*] Launching using local environment (.venv)...\"\n"
            "    exec .venv/bin/python server.py\n"
            "fi\n"
            "PY_CMD=\"\"\n"
            "if command -v python3 >/dev/null 2>&1; then\n"
            "    PY_CMD=\"python3\"\n"
            "elif command -v python >/dev/null 2>&1; then\n"
            "    PY_CMD=\"python\"\n"
            "fi\n"
            "if [ -z \"$PY_CMD\" ]; then\n"
            "    echo \"[!] Python 3 not found. Please install Python 3.10+.\"\n"
            "    exit 1\n"
            "fi\n"
            "if \"$PY_CMD\" -c \"import fastapi, chromadb, sentence_transformers, httpx, uvicorn\" 2>/dev/null; then\n"
            "    echo \"[*] Dependencies verified. Launching Assistant...\"\n"
            "    exec \"$PY_CMD\" server.py\n"
            "fi\n"
            "echo \"[*] Initializing local environment (.venv)...\"\n"
            "\"$PY_CMD\" -m venv --system-site-packages .venv\n"
            "echo \"[*] Installing required packages into local environment...\"\n"
            ".venv/bin/pip install -r requirements.txt\n"
            "echo \"[*] Launching Standalone Assistant...\"\n"
            "exec .venv/bin/python server.py\n"
        )
        self._safe_write_text(bundle_dir / "start.sh", launcher_sh, encoding="utf-8")
        self._safe_write_text(bundle_dir / "run.sh", launcher_sh, encoding="utf-8")

        dockerfile = (
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt .\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . .\n"
            "EXPOSE 8000\n"
            "CMD [\"python\", \"server.py\"]\n"
        )
        self._safe_write_text(bundle_dir / "Dockerfile", dockerfile, encoding="utf-8")

        # 8. Write Installation & Setup Guide
        self._safe_write_text(
            bundle_dir / "INSTALL_GUIDE.md",
            self._generate_install_guide(session.model_name),
            encoding="utf-8"
        )

        # 9. Smart Hybrid ZIP Generation (Instant image archiving + deflated code/data)
        zip_file_path = self.output_dir / f"rag_package_{session.session_id}.zip"
        pre_compressed_exts = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp", ".zip", ".tar", ".gz"}
        
        server_py = bundle_dir / "server.py"
        server_mtime = server_py.stat().st_mtime if server_py.exists() else 0

        # Check if existing archive is fresh, valid, and clean of backslash paths
        if zip_file_path.exists():
            try:
                if zip_file_path.stat().st_size > 1024 and zip_file_path.stat().st_mtime >= server_mtime:
                    with zipfile.ZipFile(zip_file_path, "r") as z_check:
                        names = set(z_check.namelist())
                        if "start.bat" in names and "server.py" in names and not any("\\" in n for n in names):
                            return zip_file_path
            except Exception:
                pass

        tmp_zip_path = zip_file_path.with_suffix(".zip.tmp")
        try:
            with zipfile.ZipFile(tmp_zip_path, "w") as zip_out:
                for root, _, files in os.walk(bundle_dir):
                    for file in files:
                        full_p = Path(root) / file
                        # Skip volatile runtime lock/port/tmp files
                        if full_p.name.endswith(".tmp") or full_p.name.endswith(".lock") or full_p.name == ".port":
                            continue
                        rel_path = full_p.relative_to(bundle_dir)
                        # CRITICAL: Windows ZIP standard requires forward slashes for entry names
                        arc_name = str(rel_path).replace("\\", "/")
                        comp_type = zipfile.ZIP_STORED if full_p.suffix.lower() in pre_compressed_exts else zipfile.ZIP_DEFLATED
                        zip_out.write(full_p, arcname=arc_name, compress_type=comp_type)
            
            # Atomic file replacement so incomplete writes never reach the browser/client
            if tmp_zip_path.exists():
                if zip_file_path.exists():
                    try:
                        zip_file_path.unlink()
                    except Exception:
                        pass
                tmp_zip_path.replace(zip_file_path)
        except Exception as ze:
            print(f"[!] Zip creation warning: {ze}")
            if tmp_zip_path.exists():
                try:
                    tmp_zip_path.unlink()
                except Exception:
                    pass

        return zip_file_path
