import os
import shutil
import zipfile
from pathlib import Path
from typing import Optional
from server.sessions.session_manager import RAGSession


class RAGPackager:
    """
    Bundles a RAG session into a standalone, turnkey production ZIP package.
    """

    def __init__(self, export_output_dir: Path | str = "./data/exports"):
        self.output_dir = Path(export_output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _generate_standalone_server_code(self, model_name: str, embedding_model: str) -> str:
        return f'''"""
Standalone Production RAG Server
Auto-generated by Autonomous RAG Factory
"""
import os
import uvicorn
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from typing import List, Optional

# Embedded Core Logic
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings
import httpx

app = FastAPI(title="Self-Hosted Production RAG API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_NAME = "{model_name}"
EMBEDDING_MODEL = "{embedding_model}"
DB_PATH = Path("./vector_db")

print(f"📦 Loading Local Embedding Model: {{EMBEDDING_MODEL}}...")
embedder = SentenceTransformer(EMBEDDING_MODEL)

print(f"🗄️ Connecting to Embedded ChromaDB at: {{DB_PATH}}...")
chroma_client = chromadb.PersistentClient(path=str(DB_PATH), settings=Settings(anonymized_telemetry=False))
collections = chroma_client.list_collections()
collection = collections[0] if collections else chroma_client.get_or_create_collection("rag_knowledge_base")

class QueryRequest(BaseModel):
    question: str
    top_k: Optional[int] = 3

class Citation(BaseModel):
    source_file: str
    relevance_score: float
    text: str

class QueryResponse(BaseModel):
    answer: str
    citations: List[Citation]
    grounded: bool

@app.post("/api/query", response_model=QueryResponse)
async def query_rag(req: QueryRequest):
    query_vec = embedder.encode(req.question, convert_to_numpy=True).tolist()
    results = collection.query(query_embeddings=[query_vec], n_results=req.top_k, include=["documents", "metadatas", "distances"])
    
    citations = []
    relevant_chunks = []
    if results["ids"] and len(results["ids"][0]) > 0:
        for i in range(len(results["ids"][0])):
            dist = results["distances"][0][i]
            sim = max(0.0, 1.0 - dist)
            doc_text = results["documents"][0][i]
            meta = results["metadatas"][0][i]
            if sim >= 0.20:
                citations.append(Citation(source_file=meta.get("source_file", "unknown"), relevance_score=round(sim, 4), text=doc_text))
                relevant_chunks.append(f"[Document: {{meta.get('source_file', 'unknown')}}]\\n{{doc_text}}")

    if not relevant_chunks:
        return QueryResponse(answer="I could not find any information about this in the documentation.", citations=[], grounded=False)

    context_str = "\\n\\n".join(relevant_chunks)
    prompt = f"Context:\\n{{context_str}}\\n\\nQuestion: {{req.question}}\\n\\nAnswer based only on the context:"
    
    system_msg = "You are a precise enterprise assistant. Answer directly using only facts from the context."
    payload = {{
        "model": MODEL_NAME,
        "messages": [{{"role": "system", "content": system_msg}}, {{"role": "user", "content": prompt}}],
        "stream": False,
        "options": {{"temperature": 0.1, "num_ctx": 4096, "num_gpu": 99}}
    }}

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            res = await client.post("http://localhost:11434/api/chat", json=payload)
            res.raise_for_status()
            ans_text = res.json().get("message", {{}}).get("content", "").strip()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ollama error: {{str(e)}}. Make sure Ollama is running.")

    return QueryResponse(answer=ans_text, citations=citations, grounded=True)

@app.get("/", response_class=HTMLResponse)
def serve_ui():
    ui_path = Path("./index.html")
    if ui_path.exists():
        return ui_path.read_text(encoding="utf-8")
    return "<h1>Production RAG API is Running! Open /docs for API schema.</h1>"

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

    def _generate_standalone_ui(self, model_name: str) -> str:
        return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Enterprise RAG Assistant</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root {{
      --bg: #0b0f19;
      --card: #111827;
      --accent: #3b82f6;
      --text: #f9fafb;
      --muted: #9ca3af;
      --border: #1f2937;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; font-family: 'Inter', sans-serif; }}
    body {{ background: var(--bg); color: var(--text); display: flex; flex-direction: column; height: 100vh; }}
    header {{ padding: 1rem 2rem; background: var(--card); border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; }}
    .badge {{ background: #1e3a8a; color: #93c5fd; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.8rem; }}
    #chat-box {{ flex: 1; overflow-y: auto; padding: 2rem; display: flex; flex-direction: column; gap: 1.25rem; }}
    .msg {{ max-width: 80%; padding: 1rem 1.25rem; border-radius: 0.75rem; line-height: 1.5; }}
    .user-msg {{ background: var(--accent); color: #fff; align-self: flex-end; }}
    .bot-msg {{ background: var(--card); border: 1px solid var(--border); align-self: flex-start; }}
    .citations {{ margin-top: 0.75rem; padding-top: 0.75rem; border-top: 1px solid var(--border); font-size: 0.8rem; color: var(--muted); }}
    .citation-tag {{ display: inline-block; background: #1f2937; padding: 0.2rem 0.5rem; border-radius: 4px; margin-right: 0.4rem; margin-top: 0.2rem; }}
    #input-form {{ padding: 1.25rem 2rem; background: var(--card); border-top: 1px solid var(--border); display: flex; gap: 0.75rem; }}
    input {{ flex: 1; padding: 0.85rem 1.25rem; border-radius: 0.5rem; border: 1px solid var(--border); background: #1f2937; color: #fff; outline: none; font-size: 1rem; }}
    button {{ background: var(--accent); color: white; border: none; padding: 0.85rem 1.5rem; border-radius: 0.5rem; font-weight: 600; cursor: pointer; }}
    button:hover {{ background: #2563eb; }}
  </style>
</head>
<body>
  <header>
    <h2>⚡ Enterprise Knowledge Assistant</h2>
    <span class="badge">Model: {model_name}</span>
  </header>
  <div id="chat-box">
    <div class="msg bot-msg">Hello! I am your private, grounded enterprise knowledge assistant. Ask me anything about your documents.</div>
  </div>
  <form id="input-form">
    <input type="text" id="user-input" placeholder="Ask a question about your documents..." required autocomplete="off">
    <button type="submit" id="send-btn">Send</button>
  </form>
  <script>
    const form = document.getElementById('input-form');
    const input = document.getElementById('user-input');
    const chat = document.getElementById('chat-box');

    form.addEventListener('submit', async (e) => {{
      e.preventDefault();
      const q = input.value.trim();
      if (!q) return;

      chat.innerHTML += `<div class="msg user-msg">${{q}}</div>`;
      input.value = '';
      chat.scrollTop = chat.scrollHeight;

      const botId = 'bot-' + Date.now();
      chat.innerHTML += `<div class="msg bot-msg" id="${{botId}}">Thinking...</div>`;
      chat.scrollTop = chat.scrollHeight;

      try {{
        const res = await fetch('/api/query', {{
          method: 'POST',
          headers: {{ 'Content-Type': 'application/json' }},
          body: JSON.stringify({{ question: q, top_k: 3 }})
        }});
        const data = await res.json();
        let citationsHtml = '';
        if (data.citations && data.citations.length > 0) {{
          citationsHtml = '<div class="citations"><b>Sources:</b><br>' + 
            data.citations.map(c => `<span class="citation-tag">📄 ${{c.source_file}} (${{Math.round(c.relevance_score * 100)}}%)</span>`).join('') + '</div>';
        }}
        document.getElementById(botId).innerHTML = data.answer.replace(/\\n/g, '<br>') + citationsHtml;
      }} catch (err) {{
        document.getElementById(botId).innerText = "Error contacting API: " + err.message;
      }}
      chat.scrollTop = chat.scrollHeight;
    }});
  </script>
</body>
</html>
'''

    def _generate_install_guide(self, model_name: str) -> str:
        return f'''# 🚀 Self-Hosted Production RAG Deployment Guide

This package contains your fully indexed, standalone enterprise RAG pipeline.

---

## ⚡ Option 1: One-Click Quick Start (Windows)
1. Make sure **Ollama** is running on your machine:
   ```bash
   ollama pull {model_name}
   ```
2. Double-click **`run.bat`** (or run `.\\run.bat` in PowerShell).
3. Open your browser to: **`http://localhost:8000`**

---

## 🐧 Option 2: Linux / macOS Startup
1. Make executable and run:
   ```bash
   chmod +x run.sh
   ./run.sh
   ```
2. Open **`http://localhost:8000`**

---

## 🐳 Option 3: Docker Deployment
```bash
docker compose up --build
```
'''

    def create_package(self, session: RAGSession) -> Path:
        """
        Creates the complete standalone ZIP package from an active session.
        """
        bundle_dir = session.session_dir / "standalone_bundle"
        if bundle_dir.exists():
            shutil.rmtree(bundle_dir)
        bundle_dir.mkdir(parents=True, exist_ok=True)

        # 1. Copy the pre-indexed ChromaDB vector store
        dest_db = bundle_dir / "vector_db"
        shutil.copytree(session.db_dir, dest_db)

        # 2. Write Standalone Server & UI
        (bundle_dir / "server.py").write_text(
            self._generate_standalone_server_code(session.model_name, "all-MiniLM-L6-v2"),
            encoding="utf-8"
        )
        (bundle_dir / "index.html").write_text(
            self._generate_standalone_ui(session.model_name),
            encoding="utf-8"
        )

        # 3. Write requirements.txt
        requirements_txt = (
            "fastapi>=0.110.0\n"
            "uvicorn>=0.28.0\n"
            "pydantic>=2.6.0\n"
            "chromadb>=0.4.24\n"
            "sentence-transformers>=2.6.0\n"
            "httpx>=0.27.0\n"
        )
        (bundle_dir / "requirements.txt").write_text(requirements_txt, encoding="utf-8")

        # 4. Write run.bat (Windows Launcher)
        run_bat = (
            "@echo off\n"
            "echo Starting Production RAG Server...\n"
            "if not exist .venv (\n"
            "    echo Creating virtual environment...\n"
            "    python -m venv .venv\n"
            "    call .venv\\Scripts\\activate.bat\n"
            "    pip install -r requirements.txt\n"
            ") else (\n"
            "    call .venv\\Scripts\\activate.bat\n"
            ")\n"
            "python server.py\n"
            "pause\n"
        )
        (bundle_dir / "run.bat").write_text(run_bat, encoding="utf-8")

        # 5. Write run.sh (Linux/Mac Launcher)
        run_sh = (
            "#!/bin/bash\n"
            "echo 'Starting Production RAG Server...'\n"
            "if [ ! -d '.venv' ]; then\n"
            "    python3 -m venv .venv\n"
            "    source .venv/bin/activate\n"
            "    pip install -r requirements.txt\n"
            "else\n"
            "    source .venv/bin/activate\n"
            "fi\n"
            "python server.py\n"
        )
        (bundle_dir / "run.sh").write_text(run_sh, encoding="utf-8")

        # 6. Write Dockerfile
        dockerfile = (
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt .\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . .\n"
            "EXPOSE 8000\n"
            "CMD [\"python\", \"server.py\"]\n"
        )
        (bundle_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")

        # 7. Write Installation & Setup Guide
        (bundle_dir / "INSTALL_GUIDE.md").write_text(
            self._generate_install_guide(session.model_name),
            encoding="utf-8"
        )

        # 8. Compress into ZIP
        zip_file_path = self.output_dir / f"rag_package_{session.session_id}.zip"
        with zipfile.ZipFile(zip_file_path, "w", zipfile.ZIP_DEFLATED) as zip_out:
            for root, _, files in os.walk(bundle_dir):
                for file in files:
                    full_p = Path(root) / file
                    arc_name = full_p.relative_to(bundle_dir)
                    zip_out.write(full_p, arcname=arc_name)

        return zip_file_path
