import os
import shutil
import zipfile
from pathlib import Path
from typing import Optional
from server.sessions.session_manager import RAGSession


class RAGPackager:
    """
    Bundles a RAG session into a standalone, turnkey production ZIP package.
    """

    def __init__(self, export_output_dir: Path | str = "./data/exports"):
        self.output_dir = Path(export_output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _generate_standalone_server_code(self, model_name: str, embedding_model: str, indexed_files: list) -> str:
        files_json = str(indexed_files)
        return f'''"""
Standalone Production RAG Server with Multi-Turn Memory & Attention Reranking
Auto-generated by Autonomous RAG Factory (Mi:RAG)
"""
import os
import re
import uuid
import shutil
import uvicorn
from pathlib import Path
from fastapi import FastAPI, HTTPException, Request, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import List, Optional, Dict, Any

from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings
import httpx

app = FastAPI(title="Standalone Turnkey RAG Assistant", version="2.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_NAME = "{model_name}"
EMBEDDING_MODEL = "{embedding_model}"
DB_PATH = Path("./vector_db")
IMAGES_DIR = Path("./images")
INDEXED_FILES = {files_json}

IMAGES_DIR.mkdir(parents=True, exist_ok=True)
if IMAGES_DIR.exists():
    app.mount("/images", StaticFiles(directory=str(IMAGES_DIR)), name="images")

print(f"📦 Loading Local Embedding Model: {{EMBEDDING_MODEL}}...")
embedder = SentenceTransformer(EMBEDDING_MODEL)

print(f"🗄️ Connecting to Embedded ChromaDB at: {{DB_PATH}}...")
chroma_client = chromadb.PersistentClient(path=str(DB_PATH), settings=Settings(anonymized_telemetry=False))
collections = chroma_client.list_collections()
collection = collections[0] if collections else chroma_client.get_or_create_collection("rag_knowledge_base")

# Server-side conversation memory buffer
SERVER_MEMORY = []

class ChatRequest(BaseModel):
    message: str
    top_k: Optional[int] = 6
    history: Optional[List[Dict[str, Any]]] = None

class Citation(BaseModel):
    source_file: str
    relevance: float
    text: str

class ImageMatch(BaseModel):
    url: str
    filename: str
    source_file: str
    relevance: float

class ChatResponse(BaseModel):
    answer: str
    confidence_score: float
    is_grounded: bool
    citations: List[Citation]
    images: List[ImageMatch]
    query_image_url: Optional[str] = None

def apply_attention_reranking(query: str, raw_chunks: list, history: list) -> list:
    """Attention-weighted context reranking using query overlap and conversation focus."""
    query_words = set(re.findall(r"\\b\\w{{3,}}\\b", query.lower()))
    history_words = set()
    if history:
        for turn in history[-2:]:
            history_words.update(re.findall(r"\\b\\w{{3,}}\\b", str(turn.get("content", "")).lower()))

    scored = []
    for chunk in raw_chunks:
        text_lower = chunk["text"].lower()
        base_sim = chunk["score"]
        
        q_overlap = sum(1 for w in query_words if w in text_lower)
        q_boost = min(0.35, (q_overlap / max(1, len(query_words))) * 0.35)

        h_overlap = sum(1 for w in history_words if w in text_lower)
        h_boost = min(0.15, (h_overlap / max(1, len(history_words))) * 0.15) if history_words else 0.0

        diag_boost = 0.05 if "[DIAGRAM" in chunk["text"] else 0.0
        att_score = base_sim + q_boost + h_boost + diag_boost
        scored.append((att_score, chunk))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [c for _, c in scored]

def extract_relevant_images(query: str, chunks: list, is_image_query: bool = False) -> list:
    visual_keywords = ["diagram", "figure", "chart", "plot", "graph", "architecture", "image", "photo", "show me", "table", "visual", "fig.", "fig "]
    explicit_visual = any(kw in query.lower() for kw in visual_keywords)

    if not is_image_query and not explicit_visual:
        has_high_diag = any("[DIAGRAM" in c["text"] and c["score"] >= 0.45 for c in chunks)
        if not has_high_diag:
            return []

    matched = []
    seen = set()
    for c in chunks:
        meta_url = c["metadata"].get("image_url", "").strip() if isinstance(c["metadata"], dict) else ""
        urls = [meta_url] if meta_url else []
        found = re.findall(r"\\[Image URL:\\s*(.*?)\\]", c["text"])
        urls.extend([u.strip() for u in found if u.strip()])

        for u in urls:
            if u and u not in seen:
                if "_page_" in u.lower() and not is_image_query and not explicit_visual:
                    continue
                seen.add(u)
                local_u = u.replace("/api/sessions/", "").split("/images/")[-1]
                served_url = f"/images/{{local_u}}" if (IMAGES_DIR / local_u).exists() else u
                p_num = c["metadata"].get("page_number", "") if isinstance(c["metadata"], dict) else ""
                caption = f"{{c['source_file']}}" + (f" (Page {{p_num}})" if p_num else "")
                matched.append(ImageMatch(
                    url=served_url,
                    filename=Path(u).name,
                    source_file=caption,
                    relevance=round(c["score"] * 100, 1)
                ))
                if len(matched) >= (3 if is_image_query else 2):
                    break
        if len(matched) >= (3 if is_image_query else 2):
            break
    return matched

@app.get("/api/info")
def get_info():
    return {{
        "model_name": MODEL_NAME,
        "embedding_model": EMBEDDING_MODEL,
        "indexed_files": INDEXED_FILES,
        "status": "online"
    }}

@app.post("/api/clear_memory")
def clear_memory():
    global SERVER_MEMORY
    SERVER_MEMORY = []
    return {{"status": "success", "message": "Memory cleared."}}

@app.post("/api/chat", response_model=ChatResponse)
async def chat_rag(request: Request):
    global SERVER_MEMORY
    content_type = request.headers.get("content-type", "")
    query_image_path = None
    query_image_url = None
    user_message = ""
    client_history = None
    top_k = 6

    if "application/json" in content_type:
        try:
            data = await request.json()
            user_message = str(data.get("message", "")).strip()
            top_k = int(data.get("top_k", 6))
            client_history = data.get("history", None)
        except Exception:
            pass
    else:
        form = await request.form()
        user_message = str(form.get("message", "")).strip()
        try:
            top_k = int(form.get("top_k", 6))
        except Exception:
            top_k = 6
        
        h_raw = form.get("history")
        if h_raw:
            try:
                import json
                client_history = json.loads(h_raw)
            except Exception:
                pass

        up_img = form.get("image")
        if up_img and hasattr(up_img, "filename") and up_img.filename:
            fname = f"query_{{uuid.uuid4().hex[:8]}}_{{up_img.filename}}"
            query_image_path = IMAGES_DIR / fname
            with open(query_image_path, "wb") as buffer:
                shutil.copyfileobj(up_img.file, buffer)
            query_image_url = f"/images/{{fname}}"

    effective_history = client_history if client_history is not None else SERVER_MEMORY

    if not user_message and not query_image_path:
        return ChatResponse(answer="Please enter a question or attach an image.", confidence_score=1.0, is_grounded=True, citations=[], images=[])

    # Check for greetings
    if user_message.lower() in ["hi", "hello", "hey", "greetings"]:
        reply = "Hello! I am your standalone, 100% private grounded enterprise RAG assistant. How can I assist you with your indexed documents today?"
        return ChatResponse(answer=reply, confidence_score=1.0, is_grounded=True, citations=[], images=[])

    query_vec = embedder.encode(user_message or "multimodal image analysis", convert_to_numpy=True).tolist()
    results = collection.query(query_embeddings=[query_vec], n_results=top_k, include=["documents", "metadatas", "distances"])

    raw_chunks = []
    if results["ids"] and len(results["ids"][0]) > 0:
        for i in range(len(results["ids"][0])):
            dist = results["distances"][0][i]
            sim = max(0.0, 1.0 - dist)
            if sim >= 0.18:
                raw_chunks.append({{
                    "text": results["documents"][0][i],
                    "metadata": results["metadatas"][0][i],
                    "source_file": results["metadatas"][0][i].get("source_file", "Document"),
                    "score": sim
                }})

    if not raw_chunks:
        return ChatResponse(
            answer="I could not find any relevant information about this in the pre-indexed documents.",
            confidence_score=0.0,
            is_grounded=False,
            citations=[],
            images=[],
            query_image_url=query_image_url
        )

    reranked_chunks = apply_attention_reranking(user_message, raw_chunks, effective_history)

    context_blocks = []
    unique_citations = {{}}
    for idx, c in enumerate(reranked_chunks[:5], start=1):
        context_blocks.append(f"--- DOCUMENT EXCERPT {{idx}} ({{c['source_file']}}) ---\\n{{c['text']}}")
        score_pct = round(c["score"] * 100, 1)
        if c["source_file"] not in unique_citations or score_pct > unique_citations[c["source_file"]]["relevance"]:
            unique_citations[c["source_file"]] = {{
                "source_file": c["source_file"],
                "relevance": score_pct,
                "text": c["text"][:200] + "..." if len(c["text"]) > 200 else c["text"]
            }}

    history_block = ""
    if effective_history:
        turns = []
        for h in effective_history[-4:]:
            r = "User" if h.get("role") == "user" else "Assistant"
            turns.append(f"{{r}}: {{h.get('content', '')}}")
        if turns:
            history_block = "RECENT CONVERSATION MEMORY (PRIOR TURNS):\\n" + "\\n".join(turns) + "\\n\\n"

    system_prompt = (
        "You are a 100% private, local offline document intelligence engine.\\n"
        "1. Deliver a direct, finished, and well-structured answer in clean Markdown.\\n"
        "2. Use conversation memory to resolve pronouns and follow-up references.\\n"
        "3. Answer ONLY using the factual context provided. Do not hallucinate."
    )

    joined_context = "\\n\\n".join(context_blocks)
    user_prompt = (
        f"KNOWLEDGE BASE CONTEXT:\\n"
        f"{{joined_context}}\\n\\n"
        f"{{history_block}}"
        f"USER QUERY: {{user_message}}\\n\\n"
        f"FINISHED GROUNDED ANSWER:"
    )

    payload = {{
        "model": MODEL_NAME,
        "messages": [{{"role": "system", "content": system_prompt}}, {{"role": "user", "content": user_prompt}}],
        "stream": False,
        "options": {{"temperature": 0.1, "num_ctx": 4096, "num_gpu": 99}}
    }}

    try:
        async with httpx.AsyncClient(timeout=90.0) as client:
            res = await client.post("http://localhost:11434/api/chat", json=payload)
            res.raise_for_status()
            ans_text = res.json().get("message", {{}}).get("content", "").strip()
    except Exception as e:
        ans_text = f"Local Ollama error: {{str(e)}}. Make sure Ollama is running (`ollama run {{MODEL_NAME}}`)."

    matched_images = extract_relevant_images(user_message, reranked_chunks, is_image_query=bool(query_image_path))

    SERVER_MEMORY.append({{"role": "user", "content": user_message or "[Visual Search]"}})
    SERVER_MEMORY.append({{"role": "assistant", "content": ans_text}})
    if len(SERVER_MEMORY) > 12:
        SERVER_MEMORY = SERVER_MEMORY[-12:]

    avg_conf = sum(c["score"] for c in reranked_chunks) / len(reranked_chunks)

    return ChatResponse(
        answer=ans_text,
        confidence_score=round(avg_conf, 4),
        is_grounded=True,
        citations=[Citation(**v) for v in unique_citations.values()],
        images=matched_images,
        query_image_url=query_image_url
    )

@app.get("/", response_class=HTMLResponse)
def serve_ui():
    ui_path = Path("./index.html")
    if ui_path.exists():
        return ui_path.read_text(encoding="utf-8")
    return "<h1>Offline Enterprise RAG Ready</h1>"

@app.post("/api/clear_memory")
def clear_memory():
    global SERVER_MEMORY
    SERVER_MEMORY = []
    return {{"status": "ok", "message": "Conversation memory cleared."}}

@app.get("/api/info")
def get_info():
    return {{
        "model_name": MODEL_NAME,
        "indexed_files": INDEXED_FILES,
        "status": "Ready",
        "features": ["attention_reranking", "conversation_memory", "local_storage", "multimodal_search"]
    }}

if __name__ == "__main__":
    import socket
    import webbrowser
    import threading

    def get_free_port(preferred=8000):
        for p in [preferred, 8001, 8080, 8088, 8888]:
            try:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    if s.connect_ex(('127.0.0.1', p)) != 0:
                        return p
            except Exception:
                pass
        return preferred

    port = get_free_port(8000)
    url = f"http://localhost:{{port}}"
    print(f"[*] Starting Standalone Enterprise RAG Assistant on {{url}} (Model: {{MODEL_NAME}})...")
    threading.Timer(1.2, lambda: webbrowser.open(url)).start()
    uvicorn.run(app, host="0.0.0.0", port=port)
'''

    def _generate_standalone_ui(self, model_name: str, session_id: str, indexed_files: list) -> str:
        portal_template = Path("web/templates/portal.html")
        if not portal_template.exists():
            portal_template = Path(__file__).parent.parent / "web" / "templates" / "portal.html"
            
        if portal_template.exists():
            content = portal_template.read_text(encoding="utf-8")
            
            # 1. Direct standalone endpoints
            content = content.replace("const pathParts = window.location.pathname.split('/');\n    const sessionId = pathParts[pathParts.length - 1];", "const sessionId = 'standalone';")
            content = content.replace("const pathParts = window.location.pathname.split('/');", "const sessionId = 'standalone';")
            content = content.replace("const sessionId = pathParts[pathParts.length - 1];", "")
            content = content.replace("`/api/sessions/${sessionId}/chat`", "'/api/chat'")
            content = content.replace("`/api/sessions/${sessionId}/clear_memory`", "'/api/clear_memory'")
            content = content.replace("`/api/sessions/${sessionId}`", "'/api/info'")
            
            # 2. Standalone Branding & Badges
            content = content.replace('<div class="session-badge" id="session-badge">Session: loading...</div>', f'<div class="session-badge">Production Engine: {model_name}</div>')
            content = content.replace('<span id="countdown-timer">Expires in: --:--:--</span>', '<span style="color:#000; font-weight:800;">● 100% Offline Private Mode</span>')
            
            # 3. Pre-render indexed documents
            files_pills = "".join([f'<div class="file-pill">📄 {Path(f).name}</div>' for f in indexed_files]) or '<div class="file-pill">📄 Knowledge Base Documents</div>'
            content = content.replace('Loading documents...', files_pills)
            
            # 4. Hide redundant download ZIP card inside standalone package
            content = content.replace('<div class="panel-title">Standalone Package</div>', '<div class="panel-title" style="display:none;"></div>')
            content = content.replace('id="download-zip-btn" class="btn-download-zip"', 'id="download-zip-btn" class="btn-download-zip" style="display:none;"')
            
            # 5. Fix relative static paths
            content = content.replace('url(\'/static/assets/skytextured.jpg\')', 'linear-gradient(135deg, #090c15 0%, #151b2e 100%)')
            content = content.replace('/static/assets/favicon.png', '')
            content = content.replace('/static/assets/favicon.ico', '')
            
            return content
        return f"<h1>Production RAG Assistant ({model_name})</h1>"

    def _generate_installer_script(self, model_name: str, embedding_model: str) -> str:
        short_name = model_name[:12]
        return f'''"""
Standalone Turnkey Pre-flight Check & Instant Setup
Auto-generated by Autonomous RAG Factory
"""
import sys
import os
import time
import json
import subprocess
import urllib.request
import urllib.error

def render_progress_bar(iteration, total, prefix="", suffix="", length=28, fill="█", empty="░"):
    if total <= 0:
        percent = 100.0
        filled_length = length
    else:
        percent = min(100.0, max(0.0, (iteration / float(total)) * 100.0))
        filled_length = int(length * iteration // total)
    bar = fill * filled_length + empty * (length - filled_length)
    sys.stdout.write(f"\\r  {{prefix}} [{{bar}}] {{percent:.1f}}% {{suffix}}")
    sys.stdout.flush()
    if iteration >= total and total > 0:
        sys.stdout.write("\\n")
        sys.stdout.flush()

def format_bytes(size_bytes):
    if not size_bytes or size_bytes <= 0:
        return "0 B"
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_bytes < 1024.0:
            return f"{{size_bytes:.1f}} {{unit}}"
        size_bytes /= 1024.0
    return f"{{size_bytes:.1f}} TB"

def check_environment():
    try:
        import fastapi
        import uvicorn
        import chromadb
        import sentence_transformers
        import httpx
        return True
    except ImportError:
        return False

def is_model_cached(model_str):
    try:
        req = urllib.request.Request("http://localhost:11434/api/tags")
        with urllib.request.urlopen(req, timeout=1.5) as res:
            if res.status == 200:
                data = json.loads(res.read().decode("utf-8"))
                models = [m.get("name", "").split(":")[0] for m in data.get("models", [])]
                models.extend([m.get("name", "") for m in data.get("models", [])])
                target_root = model_str.split(":")[0]
                return model_str in models or target_root in models
    except Exception:
        pass
    return False

env_ready = check_environment()
model_ready = is_model_cached("{model_name}")

if env_ready and model_ready:
    print("[*] Fast-start: All dependencies and local models are verified and cached.")
    sys.exit(0)

print("\\n" + "="*70)
print("       STANDALONE ENTERPRISE RAG - ONE-CLICK SETUP")
print("="*70)

if not env_ready:
    print("\\n[1/2] Installing Python dependencies (Streaming live progress)...")
    req_file = "requirements.txt"
    if os.path.exists(req_file):
        process = subprocess.Popen(
            [sys.executable, "-m", "pip", "install", "-r", req_file, "--progress-bar", "on"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
        
        start_time = time.time()
        for raw_line in process.stdout:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("Collecting"):
                pkg_name = line.replace("Collecting", "").strip().split()[0]
                sys.stdout.write(f"\\r  [Download] {{pkg_name:<35}}\\n")
                sys.stdout.flush()
            elif "Downloading" in line:
                sys.stdout.write(f"\\r    -> {{line[:60]:<60}}")
                sys.stdout.flush()
            elif line.startswith("Installing collected packages:"):
                sys.stdout.write(f"\\n  [Installing collected wheels...]\\n")
                sys.stdout.flush()
            elif line.startswith("Successfully installed"):
                sys.stdout.write(f"\\n  [OK] All dependencies configured in {{int(time.time() - start_time)}}s!\\n")
                sys.stdout.flush()
        process.wait()
else:
    print("[1/2] [OK] Core dependencies verified!")

if not model_ready:
    print(f"\\n[2/2] Downloading Local LLM: {model_name}...")
    ollama_url = "http://localhost:11434"
    try:
        pull_req = urllib.request.Request(
            f"{{ollama_url}}/api/pull",
            data=json.dumps({{"name": "{model_name}", "stream": True}}).encode("utf-8"),
            headers={{"Content-Type": "application/json"}}
        )
        with urllib.request.urlopen(pull_req, timeout=600.0) as response:
            prev_completed = 0
            last_time = time.time()
            for line in response:
                if not line:
                    continue
                chunk = json.loads(line.decode("utf-8"))
                status = chunk.get("status", "working")
                total = chunk.get("total", 0)
                completed = chunk.get("completed", 0)

                if total > 0:
                    cur_time = time.time()
                    speed_str = ""
                    eta_str = ""
                    if completed > prev_completed and (cur_time - last_time) > 0.25:
                        bytes_per_sec = (completed - prev_completed) / (cur_time - last_time)
                        if bytes_per_sec > 0:
                            speed_str = f"• {{format_bytes(bytes_per_sec)}}/s"
                            rem_seconds = int((total - completed) / bytes_per_sec)
                            eta_str = f"• ETA: {{rem_seconds}}s"
                        prev_completed = completed
                        last_time = cur_time

                    render_progress_bar(
                        completed,
                        total,
                        prefix="{short_name:<12}",
                        suffix=f"({{format_bytes(completed)}} / {{format_bytes(total)}}) {{speed_str}} {{eta_str}}"
                    )
                else:
                    sys.stdout.write(f"\\r  [*] {{status:<45}}")
                    sys.stdout.flush()
        sys.stdout.write(f"\\r  [OK] Local LLM '{model_name}' is verified, cached, and ready!\\n")
    except Exception as e:
        print(f"  [*] Model status note: {{e}}")
else:
    print(f"[2/2] [OK] Model '{model_name}' is cached and ready!")

print("\\n[*] Starting Production Assistant on http://localhost:8000 ...\\n")
'''

    def _generate_install_guide(self, model_name: str) -> str:
        return f'''# Standalone Production RAG Assistant

This package contains your turnkey, fully-indexed RAG assistant with:
- **Direct Launch into Chat Playground (Bypasses Studio/Training screen completely)**
- **Pre-Indexed Vector Database (ChromaDB)**
- **Multi-Turn Conversation Memory & LocalStorage Persistence**
- **Attention-Weighted Reranking & Anti-Hallucination Guardrails**
- **Multimodal Visual Diagram Analysis & Image Search**
- **Instant 1-Click Launch (starts in <1s once cached)**

---

## 1-Click Launch (Windows)
1. Double-click **`run.bat`**.
2. Your browser will automatically open straight into the **Chat Playground** with all your documents and memory ready!

---

## Linux / macOS Launch
1. Make executable and run:
   ```bash
   chmod +x run.sh
   ./run.sh
   ```
2. Open the URL shown in the terminal in your browser.

---

## Docker Launch
```bash
docker compose up --build
```
'''

    def create_package(self, session: RAGSession) -> Path:
        bundle_dir = session.session_dir / "standalone_bundle"
        if bundle_dir.exists():
            shutil.rmtree(bundle_dir)
        bundle_dir.mkdir(parents=True, exist_ok=True)

        dest_db = bundle_dir / "vector_db"
        shutil.copytree(session.db_dir, dest_db)

        images_dest = bundle_dir / "images"
        images_dest.mkdir(parents=True, exist_ok=True)
        if session.uploads_dir.exists():
            for img_file in session.uploads_dir.glob("*.*"):
                if img_file.suffix.lower() in [".png", ".jpg", ".jpeg", ".webp", ".bmp"]:
                    shutil.copy2(img_file, images_dest / img_file.name)

        # Write Standalone Server, Hydrated Direct Chat UI & Installer
        (bundle_dir / "server.py").write_text(
            self._generate_standalone_server_code(session.model_name, "all-MiniLM-L6-v2", session.indexed_files),
            encoding="utf-8"
        )
        (bundle_dir / "index.html").write_text(
            self._generate_standalone_ui(session.model_name, session.session_id, session.indexed_files),
            encoding="utf-8"
        )
        (bundle_dir / "setup.py").write_text(
            self._generate_installer_script(session.model_name, "all-MiniLM-L6-v2"),
            encoding="utf-8"
        )

        requirements_txt = (
            "fastapi>=0.110.0\n"
            "uvicorn>=0.28.0\n"
            "pydantic>=2.6.0\n"
            "chromadb>=0.4.24\n"
            "sentence-transformers>=2.6.0\n"
            "httpx>=0.27.0\n"
            "python-multipart>=0.0.9\n"
        )
        (bundle_dir / "requirements.txt").write_text(requirements_txt, encoding="utf-8")

        # Write run.bat (Instant Launch with direct Chatbot server execution)
        run_bat = (
            "@echo off\n"
            "setlocal enabledelayedexpansion\n"
            "title Standalone Enterprise RAG Assistant\n"
            "\n"
            ":: 1. Fast check if active python environment already has required modules\n"
            "python -c \"import fastapi, chromadb, sentence_transformers, httpx\" 2>nul\n"
            "if %errorlevel% equ 0 (\n"
            "    echo [OK] System environment has all packages cached. Launching Chatbot Assistant...\n"
            "    python server.py\n"
            "    exit /b\n"
            ")\n"
            "\n"
            ":: 2. Otherwise create venv inheriting system site packages if available\n"
            "if not exist .venv (\n"
            "    echo [1/2] Setting up local environment...\n"
            "    python -m venv --system-site-packages .venv\n"
            ")\n"
            "call .venv\\Scripts\\activate.bat\n"
            "python setup.py\n"
            "python server.py\n"
            "pause\n"
        )
        (bundle_dir / "run.bat").write_text(run_bat, encoding="utf-8")

        # Write run.sh (Linux/Mac Launcher)
        run_sh = (
            "#!/bin/bash\n"
            "python3 -c \"import fastapi, chromadb, sentence_transformers, httpx\" 2>/dev/null\n"
            "if [ $? -eq 0 ]; then\n"
            "    echo '[OK] System environment has all packages cached. Launching Chatbot Assistant...'\n"
            "    python3 server.py\n"
            "    exit 0\n"
            "fi\n"
            "if [ ! -d '.venv' ]; then\n"
            "    python3 -m venv --system-site-packages .venv\n"
            "fi\n"
            "source .venv/bin/activate\n"
            "python3 setup.py\n"
            "python3 server.py\n"
        )
        (bundle_dir / "run.sh").write_text(run_sh, encoding="utf-8")

        dockerfile = (
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt .\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . .\n"
            "EXPOSE 8000\n"
            "CMD [\"python\", \"server.py\"]\n"
        )
        (bundle_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")

        # 8. Write Installation & Setup Guide
        (bundle_dir / "INSTALL_GUIDE.md").write_text(
            self._generate_install_guide(session.model_name),
            encoding="utf-8"
        )

        # 9. Compress into ZIP
        zip_file_path = self.output_dir / f"rag_package_{session.session_id}.zip"
        with zipfile.ZipFile(zip_file_path, "w", zipfile.ZIP_DEFLATED) as zip_out:
            for root, _, files in os.walk(bundle_dir):
                for file in files:
                    full_p = Path(root) / file
                    arc_name = full_p.relative_to(bundle_dir)
                    zip_out.write(full_p, arcname=arc_name)

        return zip_file_path
